/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the Record JSON OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  NotFound,
  type Operation,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { type RecordJsonClient, type RecordJsonError, run } from "../client.ts";
import { Entry } from "../schemas.ts";

// ===========================================================================
// entries.get — GET /entries/{id}
// ===========================================================================

export const GetEntryInput = Schema.Struct({
  id: Schema.String,
});
export interface GetEntryInput extends Schema.Schema.Type<
  typeof GetEntryInput
> {}

const getErrors = [NotFound] as const;

const getOp: Operation<typeof GetEntryInput, typeof Entry, typeof getErrors> = {
  id: "entries.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/entries/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: GetEntryInput,
  output: Entry,
  errors: getErrors,
};

/** Fetch an entry by id. */
export const get = (
  input: GetEntryInput,
): Effect.Effect<Entry, RecordJsonError<typeof getErrors>, RecordJsonClient> =>
  run(getOp, input);
