/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - wire shapes → the Array Success OpenAPI spec + the generator's schema mapping
 *   - redaction / decoding behavior → @hourglass-financial/api-factory-core
 *
 * Wire field names are kept verbatim (snake_case) for 1:1 fidelity with the
 * Array Success API; secret fields are typed through core's `Secret` so tokens decode
 * to `Redacted<string>` and never print.
 */
import * as Schema from "effect/Schema";

// ---------------------------------------------------------------------------
// Identities
// ---------------------------------------------------------------------------

/** A connected identity. */
export const Identity = Schema.Struct({
  id: Schema.String,
  type: Schema.String,
});
export interface Identity extends Schema.Schema.Type<typeof Identity> {}
