const fixedEmitterBindings = [
  "Schema",
  "Effect",
  "Stream",
  "Context",
  "Layer",
  "Redacted",
  "Config",
  "FetchHttpClient",
  "HttpClient",
  "Operation",
  "Pagination",
  "Secret",
  "Meta",
  "MetaKey",
  "RedactedValue",
  "byCode",
  "run",
  "credentialsFromEnv",
  "credentialsOf",
  "config",
  "DEFAULT_BASE_URL",
  "Credentials",
  "STATUS_ERRORS",
  "CODE_ERRORS",
  "DEFAULT_ERRORS",
  "operations",
] as const;

export const reservedEmitterBindings = (prefix: string): ReadonlySet<string> =>
  new Set([
    ...fixedEmitterBindings,
    `${prefix}Client`,
    `${prefix}ClientShape`,
    `${prefix}ClientOptions`,
    `${prefix}Error`,
    `${prefix}Config`,
    `Unknown${prefix}Error`,
    `${prefix}TransportError`,
    `${prefix}DecodeError`,
    `${prefix}ExtraError`,
    `${prefix}UniversalError`,
  ]);
