/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the Northstar OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  NotFound,
  type Operation,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { type NorthstarClient, type NorthstarError, run } from "../client.ts";
import { Widget } from "../schemas.ts";

// ===========================================================================
// widgets.get — GET /widgets/{id}
// ===========================================================================

export const GetWidgetInput = Schema.Struct({
  id: Schema.String,
});
export interface GetWidgetInput extends Schema.Schema.Type<
  typeof GetWidgetInput
> {}

const getErrors = [NotFound] as const;

const getOp: Operation<typeof GetWidgetInput, typeof Widget, typeof getErrors> =
  {
    id: "widgets.get",
    method: "GET",
    retry: "transient",
    pathTemplate: "/widgets/{id}",
    pathParams: ["id"],
    queryParams: [],
    input: GetWidgetInput,
    output: Widget,
    errors: getErrors,
  };

/** Fetch a widget by id. */
export const get = (
  input: GetWidgetInput,
): Effect.Effect<Widget, NorthstarError<typeof getErrors>, NorthstarClient> =>
  run(getOp, input);
