/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the Glyph OpenAPI spec
 *   - request execution, retry, redaction → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  NotFound,
  type Operation,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { type GlyphClient, type GlyphError, run } from "../client.ts";
import { DocumentEnvelope } from "../schemas.ts";

// ===========================================================================
// documents.get — GET /documents/{id}
// ===========================================================================

export const GetDocumentInput = Schema.Struct({
  id: Schema.String,
  filter: Schema.optional(Schema.Union([Schema.String, Schema.Number])),
});
export interface GetDocumentInput extends Schema.Schema.Type<
  typeof GetDocumentInput
> {}

const getErrors = [NotFound] as const;

const getOp: Operation<
  typeof GetDocumentInput,
  typeof DocumentEnvelope,
  typeof getErrors
> = {
  id: "documents.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/documents/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: GetDocumentInput,
  output: DocumentEnvelope,
  errors: getErrors,
};

/** Fetch a document. */
export const get = (
  input: GetDocumentInput,
): Effect.Effect<DocumentEnvelope, GlyphError<typeof getErrors>, GlyphClient> =>
  run(getOp, input);

// ===========================================================================
// documents.remove — DELETE /documents/{id}
// ===========================================================================

export const RemoveDocumentInput = Schema.Struct({
  id: Schema.String,
});
export interface RemoveDocumentInput extends Schema.Schema.Type<
  typeof RemoveDocumentInput
> {}

const removeErrors = [NotFound] as const;

const removeOp: Operation<
  typeof RemoveDocumentInput,
  typeof Schema.Void,
  typeof removeErrors
> = {
  id: "documents.remove",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/documents/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: RemoveDocumentInput,
  output: Schema.Void,
  errors: removeErrors,
};

/** Remove a document. */
export const remove = (
  input: RemoveDocumentInput,
): Effect.Effect<void, GlyphError<typeof removeErrors>, GlyphClient> =>
  run(removeOp, input);
