/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the Quarry OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  NotFound,
  type Operation,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { type QuarryClient, type QuarryError, run } from "../client.ts";

// ===========================================================================
// artifacts.delete — DELETE /artifacts/{id}
// ===========================================================================

export const DeleteArtifactInput = Schema.Struct({
  id: Schema.String,
});
export interface DeleteArtifactInput extends Schema.Schema.Type<
  typeof DeleteArtifactInput
> {}

const deleteErrors = [NotFound] as const;

const deleteOp: Operation<
  typeof DeleteArtifactInput,
  typeof Schema.Void,
  typeof deleteErrors
> = {
  id: "artifacts.delete",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/artifacts/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: DeleteArtifactInput,
  output: Schema.Void,
  errors: deleteErrors,
};

/** Permanently delete an artifact. */
const deleteArtifact = (
  input: DeleteArtifactInput,
): Effect.Effect<void, QuarryError<typeof deleteErrors>, QuarryClient> =>
  run(deleteOp, input);

// `delete` is a reserved word as a declaration name but a legal export name;
// the rename-export keeps the public surface on the API's own verb.
export { deleteArtifact as delete };
