/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - error codes / status table → the Mosaic OpenAPI spec + generator mapping
 *   - error base classes, retry classification → @hourglass-financial/api-factory-core
 */
import {
  byCode,
  type ClassifiedErrorClass,
  DEFAULT_ERRORS as CORE_DEFAULT_ERRORS,
  Meta,
  MetaKey,
  RedactedValue,
  STATUS_ERRORS as CORE_STATUS_ERRORS,
} from "@hourglass-financial/api-factory-core";
import * as Schema from "effect/Schema";

// Universal status-mapped errors, re-exported so consumers import them from the
// client package rather than reaching into core.
export { NotFound } from "@hourglass-financial/api-factory-core";

// ---------------------------------------------------------------------------
// Client-owned fallback / wrapper errors
// ---------------------------------------------------------------------------

/**
 * A Mosaic error the SDK does not (yet) model — an unmapped status or an
 * unknown discriminator code. Its presence signals a spec gap to be patched.
 * The raw body is preserved for diagnosis behind `Redacted` — validation
 * envelopes can echo submitted values, so it must not print from a logged
 * error; unwrap deliberately with `Redacted.value(error.body)`. The `message`
 * is the API's own human-facing text and stays printable.
 */
export class UnknownMosaicError extends Schema.TaggedErrorClass<UnknownMosaicError>()(
  "UnknownMosaicError",
  {
    status: Schema.optional(Schema.Number),
    code: Schema.optional(Schema.String),
    message: Schema.String,
    body: RedactedValue,
  },
) {
  readonly [MetaKey] = Meta.unknown;
}

/**
 * A wire-level transport failure (DNS, connect/read timeout, socket reset).
 * `cause` is core's secret-free `TransportFailure` summary — never the raw
 * `HttpClientError`, whose `reason` carries the full request (encoded body
 * and auth header included).
 */
export class MosaicTransportError extends Schema.TaggedErrorClass<MosaicTransportError>()(
  "MosaicTransportError",
  { message: Schema.String, cause: Schema.Unknown },
) {
  readonly [MetaKey] = Meta.transport;
}

/**
 * A request or response the SDK could not encode, read, or decode against its
 * schema. The offending value and the underlying issue are preserved for
 * diagnosis but wrapped in `Redacted` — a token-bearing response that fails
 * decode on an unrelated field must not leak secrets through a logged error.
 * Unwrap deliberately: `Redacted.value(error.body)` / `Redacted.value(error.cause)`.
 */
export class MosaicDecodeError extends Schema.TaggedErrorClass<MosaicDecodeError>()(
  "MosaicDecodeError",
  {
    message: Schema.String,
    body: Schema.optional(RedactedValue),
    cause: RedactedValue,
  },
) {
  readonly [MetaKey] = Meta.parse;
}

// ---------------------------------------------------------------------------
// Matcher tables (consumed by client.ts via core's makeMatchError)
// ---------------------------------------------------------------------------

/** HTTP status → shared error class (core's table, re-exported). */
export const STATUS_ERRORS = CORE_STATUS_ERRORS;

/**
 * Mosaic discriminator code → typed error class, derived from each class's
 * own `code` schema literal — a map key can never disagree with the literal
 * the class validates.
 */
export const CODE_ERRORS: Readonly<Record<string, ClassifiedErrorClass>> =
  byCode([]);

/** Errors that can arise on any Mosaic operation (401/429/5xx). */
export const DEFAULT_ERRORS = CORE_DEFAULT_ERRORS;

/** Instance union of {@link DEFAULT_ERRORS}. */
export type MosaicUniversalError = InstanceType<
  (typeof DEFAULT_ERRORS)[number]
>;

/**
 * Everything a Mosaic operation can fail with *beyond* its own declared typed
 * errors: the universal defaults, the unknown fallback, and the transport /
 * decode wrappers. This is the `Extra` union threaded into core's runner.
 */
export type MosaicExtraError =
  | MosaicUniversalError
  | UnknownMosaicError
  | MosaicTransportError
  | MosaicDecodeError;
