/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * `@hourglass-financial/api-factory-mosaic` — the Mosaic client.
 *
 * Provide one layer and call tree-shakeable operations grouped by resource:
 *
 * ```ts
 * import { accounts, layerFromEnv } from "@hourglass-financial/api-factory-mosaic";
 * import { Effect } from "effect";
 *
 * const program = accounts.create({});
 * program.pipe(Effect.provide(layerFromEnv));
 * ```
 */

// Resource operation namespaces.
export * as accounts from "./resources/accounts.ts";
export * as zones from "./resources/zones.ts";

// Credentials service + credential layers.
export {
  Credentials,
  credentialsFromEnv,
  credentialsOf,
  DEFAULT_BASE_URL,
  type MosaicConfig,
} from "./config.ts";

// Client service, layers, dispatch helper, and error-channel helper.
export {
  layer,
  layerFromEnv,
  layerWith,
  run,
  type MosaicClientOptions,
  type MosaicClientShape,
  MosaicClient,
  type MosaicError,
} from "./client.ts";

// Errors — status-mapped, code-discriminated, and client-owned wrappers.
export * from "./errors.ts";

// Wire schemas (values double as types for consumers who want them).
export * from "./schemas.ts";

export { operations, type OperationName } from "./registry.ts";

// Core re-exports so consumers never import core directly: `Secret` to wrap
// request secrets, `Category` for classification helpers (`Category.hasCategory`
// narrows the error union inside `Effect.catchIf`).
export { Category, Secret } from "@hourglass-financial/api-factory-core";
