/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - wire shapes → the Mosaic OpenAPI spec + the generator's schema mapping
 *   - redaction / decoding behavior → @hourglass-financial/api-factory-core
 *
 * Wire field names are kept verbatim (snake_case) for 1:1 fidelity with the
 * Mosaic API; secret fields are typed through core's `Secret` so tokens decode
 * to `Redacted<string>` and never print.
 */
import * as Schema from "effect/Schema";

// ---------------------------------------------------------------------------
// Accounts
// ---------------------------------------------------------------------------

/** A Mosaic account. */
export const Account = Schema.Struct({
  id: Schema.String,
  name: Schema.String,
});
export interface Account extends Schema.Schema.Type<typeof Account> {}

// ---------------------------------------------------------------------------
// Zones
// ---------------------------------------------------------------------------

/** A list of zones. */
export const ZoneList = Schema.Struct({ data: Schema.Array(Schema.String) });
export interface ZoneList extends Schema.Schema.Type<typeof ZoneList> {}
