/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the Bastion OpenAPI spec
 *   - redaction, error gating, request execution → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  type Operation,
  Secret,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { type BastionClient, type BastionError, run } from "../client.ts";
import { AlphaChallenge, InvalidToken } from "../errors.ts";
import { Session } from "../schemas.ts";

// ===========================================================================
// sessions.authenticate — POST /sessions/authenticate
// ===========================================================================

export const AuthenticateInput = Schema.Struct({
  email: Schema.String,
  password: Secret,
});
export interface AuthenticateInput extends Schema.Schema.Type<
  typeof AuthenticateInput
> {}

// The endpoint returns typed discriminator errors.
const authenticateErrors = [AlphaChallenge, BadRequest, InvalidToken] as const;

const authenticateOp: Operation<
  typeof AuthenticateInput,
  typeof Session,
  typeof authenticateErrors
> = {
  id: "sessions.authenticate",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/sessions/authenticate",
  pathParams: [],
  queryParams: [],
  input: AuthenticateInput,
  output: Session,
  errors: authenticateErrors,
  constantBody: { grant_type: "password", interactive: true },
};

/** Authenticate a Bastion session. */
export const authenticate = (
  input: AuthenticateInput,
): Effect.Effect<
  Session,
  BastionError<typeof authenticateErrors>,
  BastionClient
> => run(authenticateOp, input);
