/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the Orbit OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  NotFound,
  type Operation,
  Pagination,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { type OrbitClient, type OrbitError, run } from "../client.ts";
import { Satellite, SatellitePage } from "../schemas.ts";

// ===========================================================================
// satellites.list — GET /satellites (cursor paginated)
// ===========================================================================

export const ListSatellitesInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
});
export interface ListSatellitesInput extends Schema.Schema.Type<
  typeof ListSatellitesInput
> {}

const listErrors = [NotFound] as const;

const listOp: Operation<
  typeof ListSatellitesInput,
  typeof SatellitePage,
  typeof listErrors
> = {
  id: "satellites.list",
  method: "GET",
  retry: "transient",
  pathTemplate: "/satellites",
  pathParams: [],
  queryParams: ["before", "after", "limit"],
  input: ListSatellitesInput,
  output: SatellitePage,
  errors: listErrors,
};

/** Fetch a single page of satellites. */
export const list = (
  input: ListSatellitesInput = {},
): Effect.Effect<SatellitePage, OrbitError<typeof listErrors>, OrbitClient> =>
  run(listOp, input);

const listPagination: Pagination.CursorPagination<
  ListSatellitesInput,
  SatellitePage,
  Satellite
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.meta.after,
  items: (page) => page.data,
};

/** Stream every page of satellites, following the `after` cursor. */
export const listPages = (
  input: ListSatellitesInput = {},
): Stream.Stream<SatellitePage, OrbitError<typeof listErrors>, OrbitClient> =>
  Pagination.pages(list, input, listPagination);

/** Stream every satellite across every page. */
export const listItems = (
  input: ListSatellitesInput = {},
): Stream.Stream<Satellite, OrbitError<typeof listErrors>, OrbitClient> =>
  Pagination.items(list, input, listPagination);
