/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the Envelope Variants OpenAPI spec
 *   - request execution, error gating → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  NotFound,
  type Operation,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import {
  type EnvelopeVariantsClient,
  type EnvelopeVariantsError,
  run,
} from "../client.ts";

// ===========================================================================
// events.get — GET /events
// ===========================================================================

export const GetEventInput = Schema.Struct({});
export interface GetEventInput extends Schema.Schema.Type<
  typeof GetEventInput
> {}

const getErrors = [NotFound] as const;

const getOp: Operation<
  typeof GetEventInput,
  typeof Schema.Void,
  typeof getErrors
> = {
  id: "events.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/events",
  pathParams: [],
  queryParams: [],
  input: GetEventInput,
  output: Schema.Void,
  errors: getErrors,
};

/** get events. */
export const get = (
  input: GetEventInput = {},
): Effect.Effect<
  void,
  EnvelopeVariantsError<typeof getErrors>,
  EnvelopeVariantsClient
> => run(getOp, input);
