/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - auth scheme / error envelope shape → the generator's vendor profile
 *   - request execution, retry, error gating → @hourglass-financial/api-factory-core
 *
 * Every operation flows through the single `WorkosClient.run`, assembled here
 * from one core `makeRunner` + `makeMatchError` pair. The service is the only
 * thing a consumer wires; everything else is a tree-shakeable operation import.
 */
import {
  Category,
  type ClassifiedErrorClass,
  makeMatchError,
  makeRunner,
  type Operation,
  RETRYABLE_STATUSES,
  retryAfterForStatus,
  Retry,
  type Runner,
  summarizeHttpClientError,
} from "@hourglass-financial/api-factory-core";
import * as Context from "effect/Context";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as Redacted from "effect/Redacted";
import * as Schema from "effect/Schema";
import { HttpClient } from "effect/unstable/http/HttpClient";
import * as FetchHttpClient from "effect/unstable/http/FetchHttpClient";
import { credentialsFromEnv, Credentials } from "./config.ts";
import {
  CODE_ERRORS,
  DEFAULT_ERRORS,
  STATUS_ERRORS,
  UnknownWorkosError,
  WorkosDecodeError,
  WorkosTransportError,
  type WorkosExtraError,
} from "./errors.ts";

// ---------------------------------------------------------------------------
// Error envelope + matcher
// ---------------------------------------------------------------------------

const asString = (value: unknown): string | undefined =>
  typeof value === "string" ? value : undefined;

/**
 * Normalize WorkOS's two error envelopes into one shape. `code` and the
 * OAuth-style `error` collapse to a single discriminator; `message` prefers the
 * human field of whichever envelope is present.
 */
const decodeEnvelope = (body: unknown) => {
  if (typeof body === "string") {
    return { message: body, discriminator: undefined, body };
  }
  if (typeof body === "object" && body !== null) {
    const record = body as Record<string, unknown>;
    const message =
      asString(record.message) ??
      asString(record.error_description) ??
      asString(record.error) ??
      "";
    const discriminator = asString(record.code) ?? asString(record.error);
    return { message, discriminator, body };
  }
  return { message: "", discriminator: undefined, body };
};

const matchError = makeMatchError<WorkosExtraError>({
  decodeEnvelope,
  statusErrors: STATUS_ERRORS,
  codeErrors: CODE_ERRORS,
  universalErrors: DEFAULT_ERRORS,
  retryableStatuses: RETRYABLE_STATUSES,
  retryAfterFor: (status, headers) =>
    retryAfterForStatus(status, headers, RETRYABLE_STATUSES),
  makeUnknown: ({ status, envelope }) =>
    new UnknownWorkosError({
      status,
      code: envelope.discriminator,
      message: envelope.message,
      body: envelope.body,
    }),
});

// ---------------------------------------------------------------------------
// Client service + layers
// ---------------------------------------------------------------------------

/**
 * The full, honest error channel of a WorkOS operation: its own declared typed
 * errors plus the universal defaults, `Unknown*` fallback, and transport/decode
 * wrappers. Every generated operation annotates its result with this.
 */
export type WorkosError<EC extends readonly ClassifiedErrorClass[]> =
  | InstanceType<EC[number]>
  | WorkosExtraError;

/** The single request runner every WorkOS operation is dispatched through. */
export interface WorkosClientShape {
  readonly run: Runner<WorkosExtraError>;
}

/** Context service exposing the WorkOS request runner. */
export class WorkosClient extends Context.Service<
  WorkosClient,
  WorkosClientShape
>()("@hourglass-financial/api-factory-workos/WorkosClient") {}

/** Options for building the client layer. */
export interface WorkosClientOptions {
  /** Retry policy applied to every call. Defaults to core's transient policy. */
  readonly retry?: Retry.RetryPolicy;
}

/**
 * Client layer over an injected `HttpClient` + {@link Credentials}. Use this
 * when you want to supply your own transport (e.g. a mock in tests) or a custom
 * retry policy.
 */
export const layerWith = (
  options: WorkosClientOptions = {},
): Layer.Layer<WorkosClient, never, HttpClient | Credentials> =>
  Layer.effect(
    WorkosClient,
    Effect.gen(function* () {
      const http = yield* HttpClient;
      const { apiKey, baseUrl } = yield* Credentials;
      const run = makeRunner<WorkosExtraError>({
        http,
        apiKey,
        baseUrl,
        retry: options.retry ?? Retry.defaultPolicy,
        matchError,
        // Only a genuine wire-level fault is the (retryable) transport error;
        // every other HttpClientError reason (encode, response read/decode,
        // invalid URL) is a non-retryable decode-class failure. Both carry a
        // secret-free summary, never the raw error with its embedded request.
        toTransport: (cause) =>
          Category.isTransportError(cause)
            ? new WorkosTransportError({
                message: cause.reason.message,
                cause: summarizeHttpClientError(cause),
              })
            : new WorkosDecodeError({
                message: cause.reason.message,
                cause: Redacted.make(summarizeHttpClientError(cause)),
              }),
        // The raw value and schema issue stay reachable via Redacted.value;
        // the message is fixed text so no field value can leak through it.
        toDecode: (phase, body, cause) =>
          new WorkosDecodeError({
            message:
              phase === "request-encode"
                ? "request input did not match the operation's input schema"
                : "response body did not match the operation's output schema",
            body: Redacted.make(body),
            cause: Redacted.make(cause),
          }),
      });
      return WorkosClient.of({ run });
    }),
  );

/** Client layer with the default retry policy, over injected deps. */
export const layer: Layer.Layer<WorkosClient, never, HttpClient | Credentials> =
  layerWith();

/**
 * Batteries-included layer: the default retry policy, `fetch` transport, and
 * credentials from the environment. The one line most consumers provide.
 */
export const layerFromEnv = layer.pipe(
  Layer.provide(FetchHttpClient.layer),
  Layer.provide(credentialsFromEnv),
);

// ---------------------------------------------------------------------------
// Dispatch helper used by every generated operation
// ---------------------------------------------------------------------------

/** Dispatch a declared operation through the client service. */
export const run = <
  IS extends Schema.Top & { readonly EncodingServices: never },
  OS extends Schema.Top & { readonly DecodingServices: never },
  EC extends readonly ClassifiedErrorClass[],
>(
  op: Operation<IS, OS, EC>,
  input: IS["Type"],
): Effect.Effect<
  OS["Type"],
  InstanceType<EC[number]> | WorkosExtraError,
  WorkosClient
> =>
  Effect.gen(function* () {
    const client = yield* WorkosClient;
    return yield* client.run(op, input);
  });
