/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - error codes / status table → the WorkOS OpenAPI spec + generator mapping
 *   - error base classes, retry classification → @hourglass-financial/api-factory-core
 *
 * WorkOS surfaces two error envelopes: `{ code, message }` and the OAuth-style
 * `{ error, error_description }`. Both are normalized to a single discriminator
 * by the matcher; the classes below are the ones the generator lifted from the
 * spec's discriminated `oneOf` error tables.
 */
import {
  type Category,
  type ClassifiedErrorClass,
  DEFAULT_ERRORS as CORE_DEFAULT_ERRORS,
  STATUS_ERRORS as CORE_STATUS_ERRORS,
} from "@hourglass-financial/api-factory-core";
import * as Schema from "effect/Schema";

// Universal status-mapped errors, re-exported so consumers import them from the
// client package rather than reaching into core.
export {
  BadGateway,
  BadRequest,
  ConfigError,
  Conflict,
  Forbidden,
  GatewayTimeout,
  InternalServerError,
  Locked,
  NotFound,
  ServiceUnavailable,
  TooManyRequests,
  Unauthorized,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";

// ---------------------------------------------------------------------------
// Code-discriminated authentication errors (POST /user_management/authenticate)
//
// The spec's 400/403 tables for this endpoint enumerate ~35 discriminator
// codes across every grant type; this fragment models the password-grant
// subset. The full generator emits one class per documented code, in this
// exact per-class shape.
// ---------------------------------------------------------------------------

/** 400 `invalid_credentials` — the email/password pair was rejected. */
export class InvalidCredentials extends Schema.TaggedErrorClass<InvalidCredentials>()(
  "InvalidCredentials",
  { message: Schema.String, code: Schema.Literal("invalid_credentials") },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "auth",
    retry: "none",
  };
}

/** 400 `invalid_grant` — the grant (e.g. credentials or token) is invalid. */
export class InvalidGrant extends Schema.TaggedErrorClass<InvalidGrant>()(
  "InvalidGrant",
  { message: Schema.String, code: Schema.Literal("invalid_grant") },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "auth",
    retry: "none",
  };
}

/** 400 `invalid_client` — the `client_id` is unknown or malformed. */
export class InvalidClient extends Schema.TaggedErrorClass<InvalidClient>()(
  "InvalidClient",
  { message: Schema.String, code: Schema.Literal("invalid_client") },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "auth",
    retry: "none",
  };
}

/** 403 `email_verification_required` — the user must verify their email first. */
export class EmailVerificationRequired extends Schema.TaggedErrorClass<EmailVerificationRequired>()(
  "EmailVerificationRequired",
  {
    message: Schema.String,
    code: Schema.Literal("email_verification_required"),
  },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "challenge",
    retry: "none",
  };
}

/** 403 `email_password_auth_disabled` — password auth is off for this environment. */
export class EmailPasswordAuthDisabled extends Schema.TaggedErrorClass<EmailPasswordAuthDisabled>()(
  "EmailPasswordAuthDisabled",
  {
    message: Schema.String,
    code: Schema.Literal("email_password_auth_disabled"),
  },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "auth",
    retry: "none",
  };
}

/** 403 `mfa_enrollment` — the user must enroll in MFA before continuing. */
export class MfaEnrollment extends Schema.TaggedErrorClass<MfaEnrollment>()(
  "MfaEnrollment",
  { message: Schema.String, code: Schema.Literal("mfa_enrollment") },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "challenge",
    retry: "none",
  };
}

/** 403 `mfa_challenge` — the user must complete an MFA challenge to continue. */
export class MfaChallenge extends Schema.TaggedErrorClass<MfaChallenge>()(
  "MfaChallenge",
  { message: Schema.String, code: Schema.Literal("mfa_challenge") },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "challenge",
    retry: "none",
  };
}

/** 403 `organization_selection_required` — the user must pick an organization. */
export class OrganizationSelectionRequired extends Schema.TaggedErrorClass<OrganizationSelectionRequired>()(
  "OrganizationSelectionRequired",
  {
    message: Schema.String,
    code: Schema.Literal("organization_selection_required"),
  },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "challenge",
    retry: "none",
  };
}

/** 403 `radar_challenge` — WorkOS Radar requires a bot-detection challenge. */
export class RadarChallenge extends Schema.TaggedErrorClass<RadarChallenge>()(
  "RadarChallenge",
  { message: Schema.String, code: Schema.Literal("radar_challenge") },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "challenge",
    retry: "none",
  };
}

// ---------------------------------------------------------------------------
// Client-owned fallback / wrapper errors
// ---------------------------------------------------------------------------

/**
 * A WorkOS error the SDK does not (yet) model — an unmapped status or an
 * unknown discriminator code. Its presence signals a spec gap to be patched;
 * the raw body is preserved for diagnosis.
 */
export class UnknownWorkosError extends Schema.TaggedErrorClass<UnknownWorkosError>()(
  "UnknownWorkosError",
  {
    status: Schema.optional(Schema.Number),
    code: Schema.optional(Schema.String),
    message: Schema.String,
    body: Schema.Unknown,
  },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "unknown",
    retry: "none",
  };
}

/** A wire-level transport failure (DNS, connect/read timeout, socket reset). */
export class WorkosTransportError extends Schema.TaggedErrorClass<WorkosTransportError>()(
  "WorkosTransportError",
  { message: Schema.String, cause: Schema.Unknown },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "transport",
    retry: "transient",
  };
}

/** A response body (or request input) that did not match its schema. */
export class WorkosDecodeError extends Schema.TaggedErrorClass<WorkosDecodeError>()(
  "WorkosDecodeError",
  { message: Schema.String, body: Schema.Unknown, cause: Schema.Unknown },
) {
  static readonly meta: Category.ErrorMeta = {
    category: "parse",
    retry: "none",
  };
}

// ---------------------------------------------------------------------------
// Matcher tables (consumed by client.ts via core's makeMatchError)
// ---------------------------------------------------------------------------

/** HTTP status → shared error class (core's table, re-exported). */
export const STATUS_ERRORS = CORE_STATUS_ERRORS;

/** WorkOS discriminator code → typed error class. */
export const CODE_ERRORS = {
  email_password_auth_disabled: EmailPasswordAuthDisabled,
  email_verification_required: EmailVerificationRequired,
  invalid_client: InvalidClient,
  invalid_credentials: InvalidCredentials,
  invalid_grant: InvalidGrant,
  mfa_challenge: MfaChallenge,
  mfa_enrollment: MfaEnrollment,
  organization_selection_required: OrganizationSelectionRequired,
  radar_challenge: RadarChallenge,
} as const satisfies Record<string, ClassifiedErrorClass>;

/** Errors that can arise on any WorkOS operation (401/429/5xx). */
export const DEFAULT_ERRORS = CORE_DEFAULT_ERRORS;

/** Instance union of {@link DEFAULT_ERRORS}. */
export type WorkosUniversalError = InstanceType<
  (typeof DEFAULT_ERRORS)[number]
>;

/**
 * Everything a WorkOS operation can fail with *beyond* its own declared typed
 * errors: the universal defaults, the unknown fallback, and the transport /
 * decode wrappers. This is the `Extra` union threaded into core's runner.
 */
export type WorkosExtraError =
  | WorkosUniversalError
  | UnknownWorkosError
  | WorkosTransportError
  | WorkosDecodeError;
