/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * `@hourglass-financial/api-factory-workos` — the WorkOS client.
 *
 * Provide one layer and call tree-shakeable operations grouped by resource:
 *
 * ```ts
 * import { organizations, layerFromEnv } from "@hourglass-financial/api-factory-workos";
 * import { Effect, Stream } from "effect";
 *
 * const program = Effect.gen(function* () {
 *   const org = yield* organizations.create({ name: "Acme" });
 *   const all = yield* organizations.listItems().pipe(Stream.runCollect);
 *   yield* organizations.delete({ id: org.id });
 *   return all;
 * });
 *
 * program.pipe(Effect.provide(layerFromEnv));
 * ```
 */

// Resource operation namespaces.
export * as organizations from "./resources/organizations.ts";
export * as userManagement from "./resources/user-management.ts";

// Credentials service + credential layers.
export {
  Credentials,
  credentialsFromEnv,
  credentialsOf,
  DEFAULT_BASE_URL,
  type WorkosConfig,
} from "./config.ts";

// Client service, layers, dispatch helper, and error-channel helper.
export {
  layer,
  layerFromEnv,
  layerWith,
  run,
  type WorkosClientOptions,
  type WorkosClientShape,
  WorkosClient,
  type WorkosError,
} from "./client.ts";

// Errors — status-mapped, code-discriminated, and client-owned wrappers.
export * from "./errors.ts";

// Wire schemas (values double as types for consumers who want them).
export * from "./schemas.ts";

// Redaction re-export so consumers wrap secrets without importing core directly.
export { Secret } from "@hourglass-financial/api-factory-core";
