/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the Array Success OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  NotFound,
  type Operation,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import {
  type ArraySuccessClient,
  type ArraySuccessError,
  run,
} from "../client.ts";
import { Identity } from "../schemas.ts";

// ===========================================================================
// identities.list — GET /identities
// ===========================================================================

export const ListIdentitiesInput = Schema.Struct({});
export interface ListIdentitiesInput extends Schema.Schema.Type<
  typeof ListIdentitiesInput
> {}

const listErrors = [NotFound] as const;

const listOp: Operation<
  typeof ListIdentitiesInput,
  Schema.$Array<typeof Identity>,
  typeof listErrors
> = {
  id: "identities.list",
  method: "GET",
  retry: "transient",
  pathTemplate: "/identities",
  pathParams: [],
  queryParams: [],
  input: ListIdentitiesInput,
  output: Schema.Array(Identity),
  errors: listErrors,
};

/** List identities. */
export const list = (
  input: ListIdentitiesInput = {},
): Effect.Effect<
  ReadonlyArray<Identity>,
  ArraySuccessError<typeof listErrors>,
  ArraySuccessClient
> => run(listOp, input);
