/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - auth scheme / base URL / env var names → the generator's vendor profile
 *   - credentials assembly → @hourglass-financial/api-factory-core
 */
import {
  ConfigError,
  credentialsConfig,
  credentialsFromEnvEffect,
} from "@hourglass-financial/api-factory-core";
import type * as Config from "effect/Config";
import * as Context from "effect/Context";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import type * as Redacted from "effect/Redacted";

/** Orbit production API base URL. Override with `ORBIT_API_URL`. */
export const DEFAULT_BASE_URL = "https://api.orbit.example";

/** Resolved Orbit credentials. The API key stays `Redacted` end to end. */
export interface OrbitConfig {
  readonly apiKey: Redacted.Redacted<string>;
  readonly baseUrl: string;
}

/** Context service carrying the resolved Orbit credentials. */
export class Credentials extends Context.Service<Credentials, OrbitConfig>()(
  "@hourglass-financial/api-factory-orbit/Credentials",
) {}

/** Reads `ORBIT_API_KEY` (redacted) and optional `ORBIT_API_URL` from env. */
export const config: Config.Config<OrbitConfig> = credentialsConfig({
  apiKeyVar: "ORBIT_API_KEY",
  baseUrlVar: "ORBIT_API_URL",
  defaultBaseUrl: DEFAULT_BASE_URL,
});

/**
 * Credentials from the environment. Fails with a typed {@link ConfigError} when
 * `ORBIT_API_KEY` is absent — the caller learns exactly what is missing rather
 * than getting an opaque defect.
 */
export const credentialsFromEnv: Layer.Layer<Credentials, ConfigError> =
  Layer.effect(
    Credentials,
    credentialsFromEnvEffect(
      {
        apiKeyVar: "ORBIT_API_KEY",
        baseUrlVar: "ORBIT_API_URL",
        defaultBaseUrl: DEFAULT_BASE_URL,
      },
      "Orbit credentials are not configured.",
    ).pipe(Effect.map(Credentials.of)),
  );

/** Credentials from explicit values — useful for tests and multi-tenant hosts. */
export const credentialsOf = (values: OrbitConfig): Layer.Layer<Credentials> =>
  Layer.succeed(Credentials, Credentials.of(values));
