/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - auth scheme / base URL / env var names → the generator's vendor profile
 *   - credentials assembly → @hourglass-financial/api-factory-core
 */
import {
  ConfigError,
  credentialsConfig,
  credentialsFromEnvEffect,
} from "@hourglass-financial/api-factory-core";
import type * as Config from "effect/Config";
import * as Context from "effect/Context";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import type * as Redacted from "effect/Redacted";

/** Record JSON production API base URL. Override with `RECORD_JSON_API_URL`. */
export const DEFAULT_BASE_URL = "https://api.record-json.example";

/** Resolved Record JSON credentials. The API key stays `Redacted` end to end. */
export interface RecordJsonConfig {
  readonly apiKey: Redacted.Redacted<string>;
  readonly baseUrl: string;
}

/** Context service carrying the resolved Record JSON credentials. */
export class Credentials extends Context.Service<
  Credentials,
  RecordJsonConfig
>()("@hourglass-financial/api-factory-record-json/Credentials") {}

/** Reads `RECORD_JSON_API_KEY` (redacted) and optional `RECORD_JSON_API_URL` from env. */
export const config: Config.Config<RecordJsonConfig> = credentialsConfig({
  apiKeyVar: "RECORD_JSON_API_KEY",
  baseUrlVar: "RECORD_JSON_API_URL",
  defaultBaseUrl: DEFAULT_BASE_URL,
});

/**
 * Credentials from the environment. Fails with a typed {@link ConfigError} when
 * `RECORD_JSON_API_KEY` is absent — the caller learns exactly what is missing rather
 * than getting an opaque defect.
 */
export const credentialsFromEnv: Layer.Layer<Credentials, ConfigError> =
  Layer.effect(
    Credentials,
    credentialsFromEnvEffect(
      {
        apiKeyVar: "RECORD_JSON_API_KEY",
        baseUrlVar: "RECORD_JSON_API_URL",
        defaultBaseUrl: DEFAULT_BASE_URL,
      },
      "Record JSON credentials are not configured.",
    ).pipe(Effect.map(Credentials.of)),
  );

/** Credentials from explicit values — useful for tests and multi-tenant hosts. */
export const credentialsOf = (
  values: RecordJsonConfig,
): Layer.Layer<Credentials> =>
  Layer.succeed(Credentials, Credentials.of(values));
