/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - wire shapes → the Union Success OpenAPI spec + the generator's schema mapping
 *   - redaction / decoding behavior → @hourglass-financial/api-factory-core
 *
 * Wire field names are kept verbatim (snake_case) for 1:1 fidelity with the
 * Union Success API; secret fields are typed through core's `Secret` so tokens decode
 * to `Redacted<string>` and never print.
 */
import * as Schema from "effect/Schema";

// ---------------------------------------------------------------------------
// Jobs
// ---------------------------------------------------------------------------

/** A completed job. */
export const CompletedJob = Schema.Struct({
  id: Schema.String,
  result: Schema.String,
});
export interface CompletedJob extends Schema.Schema.Type<typeof CompletedJob> {}

/** A pending job. */
export const PendingJob = Schema.Struct({
  id: Schema.String,
  status: Schema.String,
});
export interface PendingJob extends Schema.Schema.Type<typeof PendingJob> {}
