/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - wire shapes → the WorkOS OpenAPI spec + the generator's schema mapping
 *   - redaction / decoding behavior → @hourglass-financial/api-factory-core
 *
 * Wire field names are kept verbatim (snake_case) for 1:1 fidelity with the
 * WorkOS API; secret fields are typed through core's `Secret` so tokens decode
 * to `Redacted<string>` and never print.
 */
import { Secret } from "@hourglass-financial/api-factory-core";
import * as Schema from "effect/Schema";

// ---------------------------------------------------------------------------
// Organizations
// ---------------------------------------------------------------------------

/** Cursor pointers returned with every WorkOS list response. */
export const ListMetadata = Schema.Struct({
  before: Schema.NullOr(Schema.String),
  after: Schema.NullOr(Schema.String),
});
export interface ListMetadata extends Schema.Schema.Type<typeof ListMetadata> {}

/** A verified or pending domain attached to an organization. */
export const OrganizationDomain = Schema.Struct({
  object: Schema.Literal("organization_domain"),
  id: Schema.String,
  organization_id: Schema.String,
  domain: Schema.String,
  state: Schema.optional(
    Schema.Literals([
      "failed",
      "legacy_verified",
      "pending",
      "unverified",
      "verified",
    ]),
  ),
  verification_prefix: Schema.optional(Schema.String),
  verification_token: Schema.optional(Schema.String),
  verification_strategy: Schema.optional(Schema.Literals(["dns", "manual"])),
  created_at: Schema.String,
  updated_at: Schema.String,
});
export interface OrganizationDomain extends Schema.Schema.Type<
  typeof OrganizationDomain
> {}

/** A WorkOS organization. */
export const Organization = Schema.Struct({
  object: Schema.Literal("organization"),
  id: Schema.String,
  name: Schema.String,
  domains: Schema.Array(OrganizationDomain),
  metadata: Schema.Record(Schema.String, Schema.String),
  external_id: Schema.NullOr(Schema.String),
  stripe_customer_id: Schema.optional(Schema.String),
  created_at: Schema.String,
  updated_at: Schema.String,
  allow_profiles_outside_organization: Schema.optional(Schema.Boolean),
});
export interface Organization extends Schema.Schema.Type<typeof Organization> {}

/** A page of organizations. */
export const OrganizationList = Schema.Struct({
  object: Schema.Literal("list"),
  data: Schema.Array(Organization),
  list_metadata: ListMetadata,
});
export interface OrganizationList extends Schema.Schema.Type<
  typeof OrganizationList
> {}

// ---------------------------------------------------------------------------
// User Management
// ---------------------------------------------------------------------------

/** Present when a session was created via dashboard impersonation. */
export const Impersonator = Schema.Struct({
  email: Schema.String,
  reason: Schema.NullOr(Schema.String),
});
export interface Impersonator extends Schema.Schema.Type<typeof Impersonator> {}

/** OAuth provider tokens, when the session was created via an OAuth provider. */
export const OAuthTokens = Schema.Struct({
  provider: Schema.String,
  refresh_token: Secret,
  access_token: Secret,
  expires_at: Schema.Number,
  scopes: Schema.Array(Schema.String),
});
export interface OAuthTokens extends Schema.Schema.Type<typeof OAuthTokens> {}

/** A WorkOS AuthKit user. */
export const User = Schema.Struct({
  object: Schema.Literal("user"),
  id: Schema.String,
  first_name: Schema.NullOr(Schema.String),
  last_name: Schema.NullOr(Schema.String),
  name: Schema.optional(Schema.NullOr(Schema.String)),
  profile_picture_url: Schema.NullOr(Schema.String),
  email: Schema.String,
  email_verified: Schema.Boolean,
  external_id: Schema.NullOr(Schema.String),
  metadata: Schema.optional(Schema.Record(Schema.String, Schema.String)),
  last_sign_in_at: Schema.NullOr(Schema.String),
  locale: Schema.optional(Schema.NullOr(Schema.String)),
  created_at: Schema.String,
  updated_at: Schema.String,
});
export interface User extends Schema.Schema.Type<typeof User> {}

/**
 * The response from a successful authentication. `access_token` and
 * `refresh_token` decode to `Redacted<string>` — they never print.
 */
export const AuthenticationResponse = Schema.Struct({
  user: User,
  organization_id: Schema.optional(Schema.String),
  authkit_authorization_code: Schema.optional(Schema.String),
  access_token: Secret,
  refresh_token: Secret,
  authentication_method: Schema.optional(
    Schema.Literals([
      "SSO",
      "Password",
      "Passkey",
      "AppleOAuth",
      "BitbucketOAuth",
      "CrossAppAuth",
      "DiscordOAuth",
      "ExternalAuth",
      "GitHubOAuth",
      "GitLabOAuth",
      "GoogleOAuth",
      "IntuitOAuth",
      "LinkedInOAuth",
      "MicrosoftOAuth",
      "SalesforceOAuth",
      "SlackOAuth",
      "VercelMarketplaceOAuth",
      "VercelOAuth",
      "XeroOAuth",
      "MagicAuth",
      "Impersonation",
      "MigratedSession",
    ]),
  ),
  impersonator: Schema.optional(Impersonator),
  oauth_tokens: Schema.optional(OAuthTokens),
});
export interface AuthenticationResponse extends Schema.Schema.Type<
  typeof AuthenticationResponse
> {}
