/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - error codes / tables → the Bastion OpenAPI spec + generator mapping
 *
 * Table-driven consistency checks emitted alongside the client, so the
 * machine-owned package always carries a real test suite: every matcher-table
 * entry must be a classified error class, and every code-mapped class must
 * accept its own wire code. Behavioral coverage lives in `vendors/bastion`.
 */
import { checkMatcherConsistency } from "@hourglass-financial/api-factory-core";
import { describe, expect, it } from "vitest";
import {
  BastionDecodeError,
  BastionTransportError,
  CODE_ERRORS,
  DEFAULT_ERRORS,
  STATUS_ERRORS,
  UnknownBastionError,
} from "../src/errors.ts";

describe("matcher tables", () => {
  it("is internally consistent", () => {
    expect(
      checkMatcherConsistency({
        statusErrors: STATUS_ERRORS,
        codeErrors: CODE_ERRORS,
        universalErrors: DEFAULT_ERRORS,
        UnknownError: UnknownBastionError,
        TransportError: BastionTransportError,
        DecodeError: BastionDecodeError,
      }),
    ).toEqual([]);
  });
});
