/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - error codes / tables → the WorkOS OpenAPI spec + generator mapping
 *
 * Table-driven consistency checks emitted alongside the client, so the
 * machine-owned package always carries a real test suite: every matcher-table
 * entry must be a classified error class, and every code-mapped class must
 * accept its own wire code. Behavioral coverage lives in `vendors/workos`.
 */
import type { ClassifiedErrorClass } from "@hourglass-financial/api-factory-core";
import { describe, expect, it } from "vitest";
import {
  CODE_ERRORS,
  DEFAULT_ERRORS,
  STATUS_ERRORS,
  UnknownWorkosError,
  WorkosDecodeError,
  WorkosTransportError,
} from "../src/errors.ts";

const CATEGORIES = new Set([
  "auth",
  "bad-request",
  "not-found",
  "conflict",
  "unprocessable",
  "throttling",
  "server",
  "locked",
  "quota",
  "challenge",
  "config",
  "parse",
  "transport",
  "unknown",
]);
const DISPOSITIONS = new Set(["none", "transient", "throttling"]);

describe("matcher tables", () => {
  it("every status-mapped class carries a valid classification", () => {
    for (const [status, Cls] of Object.entries(STATUS_ERRORS)) {
      expect(CATEGORIES.has(Cls.meta.category), `${status}`).toBe(true);
      expect(DISPOSITIONS.has(Cls.meta.retry), `${status}`).toBe(true);
    }
  });

  it("every universal default is one of the status-mapped classes", () => {
    const statusClasses = new Set<unknown>(Object.values(STATUS_ERRORS));
    for (const Cls of DEFAULT_ERRORS) {
      expect(statusClasses.has(Cls)).toBe(true);
    }
  });

  it("every code-mapped class accepts its own wire code and is never retried", () => {
    const table: ReadonlyArray<readonly [string, ClassifiedErrorClass]> =
      Object.entries(CODE_ERRORS);
    for (const [code, Cls] of table) {
      const instance = new Cls({ message: "boom", code }) as unknown as {
        readonly code: string;
        readonly message: string;
      };
      expect(instance.code, code).toBe(code);
      expect(instance.message).toBe("boom");
      expect(Cls.meta.retry, code).toBe("none");
      expect(CATEGORIES.has(Cls.meta.category), code).toBe(true);
    }
  });

  it("the fallback and wrapper errors are classified", () => {
    expect(UnknownWorkosError.meta).toEqual({
      category: "unknown",
      retry: "none",
    });
    expect(WorkosTransportError.meta).toEqual({
      category: "transport",
      retry: "transient",
    });
    expect(WorkosDecodeError.meta).toEqual({
      category: "parse",
      retry: "none",
    });
  });
});
