/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - wire shapes → the Northstar OpenAPI spec + the generator's schema mapping
 *   - redaction / decoding behavior → @hourglass-financial/api-factory-core
 *
 * Wire field names are kept verbatim (snake_case) for 1:1 fidelity with the
 * Northstar API; secret fields are typed through core's `Secret` so tokens decode
 * to `Redacted<string>` and never print.
 */
import * as Schema from "effect/Schema";

// ---------------------------------------------------------------------------
// Widgets
// ---------------------------------------------------------------------------

/** A Northstar widget. */
export const Widget = Schema.Struct({ id: Schema.String, name: Schema.String });
export interface Widget extends Schema.Schema.Type<typeof Widget> {}
