/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - auth scheme / error envelope shape → the generator's vendor profile
 *   - request execution, retry, error gating → @hourglass-financial/api-factory-core
 *
 * Every operation flows through the single `QuarryClient.run`, assembled here
 * from one core `makeRunner` + `makeMatchError` pair. The service is the only
 * thing a consumer wires; everything else is a tree-shakeable operation import.
 */
import {
  Category,
  type ClassifiedErrorClass,
  type InputSchema,
  makeMatchError,
  makeRunner,
  type Operation,
  type OutputSchema,
  parseRetryAfter,
  Retry,
  type Runner,
  summarizeHttpClientError,
} from "@hourglass-financial/api-factory-core";
import * as Context from "effect/Context";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as Redacted from "effect/Redacted";
import * as FetchHttpClient from "effect/unstable/http/FetchHttpClient";
import { HttpClient } from "effect/unstable/http/HttpClient";
import { Credentials, credentialsFromEnv } from "./config.ts";
import {
  CODE_ERRORS,
  DEFAULT_ERRORS,
  QuarryDecodeError,
  type QuarryExtraError,
  QuarryTransportError,
  STATUS_ERRORS,
  UnknownQuarryError,
} from "./errors.ts";

// ---------------------------------------------------------------------------
// Error envelope + matcher
// ---------------------------------------------------------------------------

const asString = (value: unknown): string | undefined =>
  typeof value === "string" ? value : undefined;

/**
 * Normalize Quarry's two error envelopes into one shape. `code` and the
 * OAuth-style `error` collapse to a single discriminator; `message` prefers the
 * human field of whichever envelope is present.
 */
const decodeEnvelope = (body: unknown) => {
  if (typeof body === "string") {
    return { message: body, discriminator: undefined, body };
  }
  if (typeof body === "object" && body !== null) {
    const record = body as Record<string, unknown>;
    const message =
      asString(record.message) ??
      asString(record.error_description) ??
      asString(record.error) ??
      "";
    const discriminator = asString(record.code) ?? asString(record.error);
    return { message, discriminator, body };
  }
  return { message: "", discriminator: undefined, body };
};

const matchError = makeMatchError<QuarryExtraError>({
  decodeEnvelope,
  statusErrors: STATUS_ERRORS,
  codeErrors: CODE_ERRORS,
  universalErrors: DEFAULT_ERRORS,
  retryAfter: parseRetryAfter,
  makeUnknown: ({ status, envelope }) =>
    new UnknownQuarryError({
      status,
      code: envelope.discriminator,
      message: envelope.message,
      body: Redacted.make(envelope.body),
    }),
});

// ---------------------------------------------------------------------------
// Client service + layers
// ---------------------------------------------------------------------------

/**
 * The full, honest error channel of a Quarry operation: its own declared typed
 * errors plus the universal defaults, `Unknown*` fallback, and transport/decode
 * wrappers. Every generated operation annotates its result with this.
 */
export type QuarryError<EC extends readonly ClassifiedErrorClass[]> =
  | InstanceType<EC[number]>
  | QuarryExtraError;

/** The single request runner every Quarry operation is dispatched through. */
export interface QuarryClientShape {
  readonly run: Runner<QuarryExtraError>;
}

/** Context service exposing the Quarry request runner. */
export class QuarryClient extends Context.Service<
  QuarryClient,
  QuarryClientShape
>()("@hourglass-financial/api-factory-quarry/QuarryClient") {}

/** Options for building the client layer. */
export interface QuarryClientOptions {
  /** Retry policy applied to every call. Defaults to core's transient policy. */
  readonly retry?: Retry.RetryPolicy;
}

/**
 * Client layer over an injected `HttpClient` + {@link Credentials}. Use this
 * when you want to supply your own transport (e.g. a mock in tests) or a custom
 * retry policy.
 */
export const layerWith = (
  options: QuarryClientOptions = {},
): Layer.Layer<QuarryClient, never, HttpClient | Credentials> =>
  Layer.effect(
    QuarryClient,
    Effect.gen(function* () {
      const http = yield* HttpClient;
      const { apiKey, baseUrl } = yield* Credentials;
      const run = makeRunner<QuarryExtraError>({
        http,
        apiKey,
        baseUrl,
        retry: options.retry ?? Retry.defaultPolicy,
        matchError,
        toTransport: (cause) => {
          const failure = summarizeHttpClientError(cause);
          return Category.isTransportError(cause)
            ? new QuarryTransportError({
                message: `wire-level transport failure (${failure.method} ${failure.url})`,
                cause: failure,
              })
            : new QuarryDecodeError({
                message: `the response could not be read from the wire (${failure.reason})`,
                cause: Redacted.make(failure),
              });
        },
        toDecode: (phase, body, cause) =>
          new QuarryDecodeError({
            message:
              phase === "request-encode"
                ? "request input did not match the operation's input schema"
                : "response body did not match the operation's output schema",
            body: Redacted.make(body),
            cause: Redacted.make(cause),
          }),
      });
      return QuarryClient.of({ run });
    }),
  );

/** Client layer with the default retry policy, over injected deps. */
export const layer: Layer.Layer<QuarryClient, never, HttpClient | Credentials> =
  layerWith();

/**
 * Batteries-included layer: the default retry policy, `fetch` transport, and
 * credentials from the environment. The one line most consumers provide.
 */
export const layerFromEnv = layer.pipe(
  Layer.provide(FetchHttpClient.layer),
  Layer.provide(credentialsFromEnv),
);

// ---------------------------------------------------------------------------
// Dispatch helper used by every generated operation
// ---------------------------------------------------------------------------

/** Dispatch a declared operation through the client service. */
export const run = <
  IS extends InputSchema,
  OS extends OutputSchema,
  EC extends readonly ClassifiedErrorClass[],
>(
  op: Operation<IS, OS, EC>,
  input: IS["Type"],
): Effect.Effect<OS["Type"], QuarryError<EC>, QuarryClient> =>
  Effect.flatMap(QuarryClient, (client) => client.run(op, input));
