/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - auth scheme / error envelope shape → the generator's vendor profile
 *   - request execution, retry, error gating, envelope decode, failure wrapping → @hourglass-financial/api-factory-core
 *
 * Every operation flows through the single `BastionClient.run`, assembled here
 * from one core `makeRunner` + `makeMatchError` pair. The service is the only
 * thing a consumer wires; everything else is a tree-shakeable operation import.
 */
import {
  type ClassifiedErrorClass,
  type InputSchema,
  makeEnvelopeDecoder,
  makeMatchError,
  makeRunner,
  makeVendorAdapters,
  type Operation,
  type OutputSchema,
  parseRetryAfter,
  Retry,
  type Runner,
} from "@hourglass-financial/api-factory-core";
import * as Context from "effect/Context";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as FetchHttpClient from "effect/unstable/http/FetchHttpClient";
import { HttpClient } from "effect/unstable/http/HttpClient";
import { Credentials, credentialsFromEnv } from "./config.ts";
import {
  BastionDecodeError,
  type BastionExtraError,
  BastionTransportError,
  CODE_ERRORS,
  DEFAULT_ERRORS,
  STATUS_ERRORS,
  UnknownBastionError,
} from "./errors.ts";

// ---------------------------------------------------------------------------
// Error envelope + matcher
// ---------------------------------------------------------------------------

const adapters = makeVendorAdapters<BastionExtraError>({
  UnknownError: UnknownBastionError,
  TransportError: BastionTransportError,
  DecodeError: BastionDecodeError,
});

const matchError = makeMatchError<BastionExtraError>({
  /**
   * Normalize Bastion's two error envelopes into one shape. `code` and the
   * OAuth-style `error` collapse to a single discriminator; `message` prefers the
   * human field of whichever envelope is present.
   */
  decodeEnvelope: makeEnvelopeDecoder({
    messageFields: ["message", "error_description", "error"],
    discriminatorFields: ["code", "error"],
    stringBodyIsMessage: true,
  }),
  statusErrors: STATUS_ERRORS,
  codeErrors: CODE_ERRORS,
  universalErrors: DEFAULT_ERRORS,
  retryAfter: parseRetryAfter,
  makeUnknown: adapters.makeUnknown,
});

// ---------------------------------------------------------------------------
// Client service + layers
// ---------------------------------------------------------------------------

/**
 * The full, honest error channel of a Bastion operation: its own declared typed
 * errors plus the universal defaults, `Unknown*` fallback, and transport/decode
 * wrappers. Every generated operation annotates its result with this.
 */
export type BastionError<EC extends readonly ClassifiedErrorClass[]> =
  | InstanceType<EC[number]>
  | BastionExtraError;

/** The single request runner every Bastion operation is dispatched through. */
export interface BastionClientShape {
  readonly run: Runner<BastionExtraError>;
}

/** Context service exposing the Bastion request runner. */
export class BastionClient extends Context.Service<
  BastionClient,
  BastionClientShape
>()("@hourglass-financial/api-factory-bastion/BastionClient") {}

/** Options for building the client layer. */
export interface BastionClientOptions {
  /** Retry policy applied to every call. Defaults to core's transient policy. */
  readonly retry?: Retry.RetryPolicy;
}

/**
 * Client layer over an injected `HttpClient` + {@link Credentials}. Use this
 * when you want to supply your own transport (e.g. a mock in tests) or a custom
 * retry policy.
 */
export const layerWith = (
  options: BastionClientOptions = {},
): Layer.Layer<BastionClient, never, HttpClient | Credentials> =>
  Layer.effect(
    BastionClient,
    Effect.gen(function* () {
      const http = yield* HttpClient;
      const { apiKey, baseUrl } = yield* Credentials;
      const run = makeRunner<BastionExtraError>({
        http,
        apiKey,
        baseUrl,
        retry: options.retry ?? Retry.defaultPolicy,
        matchError,
        toTransport: adapters.toTransport,
        toDecode: adapters.toDecode,
      });
      return BastionClient.of({ run });
    }),
  );

/** Client layer with the default retry policy, over injected deps. */
export const layer: Layer.Layer<
  BastionClient,
  never,
  HttpClient | Credentials
> = layerWith();

/**
 * Batteries-included layer: the default retry policy, `fetch` transport, and
 * credentials from the environment. The one line most consumers provide.
 */
export const layerFromEnv = layer.pipe(
  Layer.provide(FetchHttpClient.layer),
  Layer.provide(credentialsFromEnv),
);

// ---------------------------------------------------------------------------
// Dispatch helper used by every generated operation
// ---------------------------------------------------------------------------

/** Dispatch a declared operation through the client service. */
export const run = <
  IS extends InputSchema,
  OS extends OutputSchema,
  EC extends readonly ClassifiedErrorClass[],
>(
  op: Operation<IS, OS, EC>,
  input: IS["Type"],
): Effect.Effect<OS["Type"], BastionError<EC>, BastionClient> =>
  Effect.flatMap(BastionClient, (client) => client.run(op, input));
