/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - auth scheme / base URL / env var names → the generator's vendor profile
 *   - config primitives → effect's `Config` / `ConfigProvider`
 */
import { ConfigError } from "@hourglass-financial/api-factory-core";
import * as Config from "effect/Config";
import * as Context from "effect/Context";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import type * as Redacted from "effect/Redacted";

/** Bastion production API base URL. Override with `BASTION_API_URL`. */
export const DEFAULT_BASE_URL = "https://api.bastion.example";

/** Resolved Bastion credentials. The API key stays `Redacted` end to end. */
export interface BastionConfig {
  readonly apiKey: Redacted.Redacted<string>;
  readonly baseUrl: string;
}

/** Context service carrying the resolved credentials. */
export class Credentials extends Context.Service<Credentials, BastionConfig>()(
  "@hourglass-financial/api-factory-bastion/Credentials",
) {}

/** Reads `BASTION_API_KEY` (redacted) and optional `BASTION_API_URL` from env. */
export const config: Config.Config<BastionConfig> = Config.all({
  apiKey: Config.redacted("BASTION_API_KEY"),
  baseUrl: Config.string("BASTION_API_URL").pipe(
    Config.withDefault(DEFAULT_BASE_URL),
  ),
});

/**
 * Credentials from the environment. Fails with a typed {@link ConfigError} when
 * `BASTION_API_KEY` is absent — the caller learns exactly what is missing rather
 * than getting an opaque defect.
 */
export const credentialsFromEnv: Layer.Layer<Credentials, ConfigError> =
  Layer.effect(
    Credentials,
    config.pipe(
      Effect.mapError(
        () =>
          new ConfigError({
            message: "Bastion credentials are not configured.",
          }),
      ),
      Effect.map(Credentials.of),
    ),
  );

/** Credentials from explicit values — useful for tests and multi-tenant hosts. */
export const credentialsOf = (
  values: BastionConfig,
): Layer.Layer<Credentials> =>
  Layer.succeed(Credentials, Credentials.of(values));
