/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * `@hourglass-financial/api-factory-bastion` — the Bastion client.
 *
 * Provide one layer and call tree-shakeable operations grouped by resource:
 *
 * ```ts
 * import { sessions, layerFromEnv } from "@hourglass-financial/api-factory-bastion";
 * import { Effect } from "effect";
 *
 * const program = sessions.authenticate({});
 * program.pipe(Effect.provide(layerFromEnv));
 * ```
 */

// Resource operation namespaces.
export * as sessions from "./resources/sessions.ts";

// Credentials service + credential layers.
export {
  Credentials,
  credentialsFromEnv,
  credentialsOf,
  DEFAULT_BASE_URL,
  type BastionConfig,
} from "./config.ts";

// Client service, layers, dispatch helper, and error-channel helper.
export {
  layer,
  layerFromEnv,
  layerWith,
  run,
  type BastionClientOptions,
  type BastionClientShape,
  BastionClient,
  type BastionError,
} from "./client.ts";

// Errors — status-mapped, code-discriminated, and client-owned wrappers.
export * from "./errors.ts";

// Wire schemas (values double as types for consumers who want them).
export * from "./schemas.ts";

// Canonical operation registry for coverage and regeneration audits.
export { operations, type OperationName } from "./registry.ts";

// Core re-exports so consumers never import core directly: `Secret` to wrap
// request secrets, `Category` for classification helpers (`Category.hasCategory`
// narrows the error union inside `Effect.catchIf`).
export { Category, Secret } from "@hourglass-financial/api-factory-core";
