/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface → the Bastion OpenAPI spec
 *   - public operation names → the generator's resolved mapping
 *
 * Canonical public operation names used by coverage and regeneration audits.
 */
export const operations = ["sessions.authenticate"] as const;

export type OperationName = (typeof operations)[number];
