/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - auth scheme / error envelope shape → the generator's vendor profile
 *   - request execution, retry, error gating, envelope decode, failure wrapping → @hourglass-financial/api-factory-core
 *
 * Every operation flows through the single `GlyphClient.run`, assembled here
 * from one core `makeRunner` + `makeMatchError` pair. The service is the only
 * thing a consumer wires; everything else is a tree-shakeable operation import.
 */
import {
  type ClassifiedErrorClass,
  type InputSchema,
  makeEnvelopeDecoder,
  makeMatchError,
  makeRunner,
  makeVendorAdapters,
  type Operation,
  type OutputSchema,
  parseRetryAfter,
  Retry,
  type Runner,
} from "@hourglass-financial/api-factory-core";
import * as Context from "effect/Context";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as FetchHttpClient from "effect/unstable/http/FetchHttpClient";
import { HttpClient } from "effect/unstable/http/HttpClient";
import { Credentials, credentialsFromEnv } from "./config.ts";
import {
  CODE_ERRORS,
  DEFAULT_ERRORS,
  GlyphDecodeError,
  type GlyphExtraError,
  GlyphTransportError,
  STATUS_ERRORS,
  UnknownGlyphError,
} from "./errors.ts";

// ---------------------------------------------------------------------------
// Error envelope + matcher
// ---------------------------------------------------------------------------

const adapters = makeVendorAdapters<GlyphExtraError>({
  UnknownError: UnknownGlyphError,
  TransportError: GlyphTransportError,
  DecodeError: GlyphDecodeError,
});

const matchError = makeMatchError<GlyphExtraError>({
  /**
   * Normalize Glyph's two error envelopes into one shape. `code` and the
   * OAuth-style `error` collapse to a single discriminator; `message` prefers the
   * human field of whichever envelope is present.
   */
  decodeEnvelope: makeEnvelopeDecoder({
    messageFields: ["message", "error_description", "error"],
    discriminatorFields: ["code", "error"],
    stringBodyIsMessage: true,
  }),
  statusErrors: STATUS_ERRORS,
  codeErrors: CODE_ERRORS,
  universalErrors: DEFAULT_ERRORS,
  retryAfter: parseRetryAfter,
  makeUnknown: adapters.makeUnknown,
});

// ---------------------------------------------------------------------------
// Client service + layers
// ---------------------------------------------------------------------------

/**
 * The full, honest error channel of a Glyph operation: its own declared typed
 * errors plus the universal defaults, `Unknown*` fallback, and transport/decode
 * wrappers. Every generated operation annotates its result with this.
 */
export type GlyphError<EC extends readonly ClassifiedErrorClass[]> =
  | InstanceType<EC[number]>
  | GlyphExtraError;

/** The single request runner every Glyph operation is dispatched through. */
export interface GlyphClientShape {
  readonly run: Runner<GlyphExtraError>;
}

/** Context service exposing the Glyph request runner. */
export class GlyphClient extends Context.Service<
  GlyphClient,
  GlyphClientShape
>()("@hourglass-financial/api-factory-glyph/GlyphClient") {}

/** Options for building the client layer. */
export interface GlyphClientOptions {
  /** Retry policy applied to every call. Defaults to core's transient policy. */
  readonly retry?: Retry.RetryPolicy;
}

/**
 * Client layer over an injected `HttpClient` + {@link Credentials}. Use this
 * when you want to supply your own transport (e.g. a mock in tests) or a custom
 * retry policy.
 */
export const layerWith = (
  options: GlyphClientOptions = {},
): Layer.Layer<GlyphClient, never, HttpClient | Credentials> =>
  Layer.effect(
    GlyphClient,
    Effect.gen(function* () {
      const http = yield* HttpClient;
      const { apiKey, baseUrl } = yield* Credentials;
      const run = makeRunner<GlyphExtraError>({
        http,
        apiKey,
        baseUrl,
        retry: options.retry ?? Retry.defaultPolicy,
        matchError,
        toTransport: adapters.toTransport,
        toDecode: adapters.toDecode,
      });
      return GlyphClient.of({ run });
    }),
  );

/** Client layer with the default retry policy, over injected deps. */
export const layer: Layer.Layer<GlyphClient, never, HttpClient | Credentials> =
  layerWith();

/**
 * Batteries-included layer: the default retry policy, `fetch` transport, and
 * credentials from the environment. The one line most consumers provide.
 */
export const layerFromEnv = layer.pipe(
  Layer.provide(FetchHttpClient.layer),
  Layer.provide(credentialsFromEnv),
);

// ---------------------------------------------------------------------------
// Dispatch helper used by every generated operation
// ---------------------------------------------------------------------------

/** Dispatch a declared operation through the client service. */
export const run = <
  IS extends InputSchema,
  OS extends OutputSchema,
  EC extends readonly ClassifiedErrorClass[],
>(
  op: Operation<IS, OS, EC>,
  input: IS["Type"],
): Effect.Effect<OS["Type"], GlyphError<EC>, GlyphClient> =>
  Effect.flatMap(GlyphClient, (client) => client.run(op, input));
