/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * `@hourglass-financial/api-factory-glyph` — the Glyph client.
 *
 * Provide one layer and call tree-shakeable operations grouped by resource:
 *
 * ```ts
 * import { documents, layerFromEnv } from "@hourglass-financial/api-factory-glyph";
 * import { Effect } from "effect";
 *
 * const program = documents.get({});
 * program.pipe(Effect.provide(layerFromEnv));
 * ```
 */

// Resource operation namespaces.
export * as documents from "./resources/documents.ts";

// Credentials service + credential layers.
export {
  Credentials,
  credentialsFromEnv,
  credentialsOf,
  DEFAULT_BASE_URL,
  type GlyphConfig,
} from "./config.ts";

// Client service, layers, dispatch helper, and error-channel helper.
export {
  layer,
  layerFromEnv,
  layerWith,
  run,
  type GlyphClientOptions,
  type GlyphClientShape,
  GlyphClient,
  type GlyphError,
} from "./client.ts";

// Errors — status-mapped, code-discriminated, and client-owned wrappers.
export * from "./errors.ts";

// Wire schemas (values double as types for consumers who want them).
export * from "./schemas.ts";

export { operations, type OperationName } from "./registry.ts";

// Core re-exports so consumers never import core directly: `Secret` to wrap
// request secrets, `Category` for classification helpers (`Category.hasCategory`
// narrows the error union inside `Effect.catchIf`).
export { Category, Secret } from "@hourglass-financial/api-factory-core";
