/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - wire shapes → the Glyph OpenAPI spec + the generator's schema mapping
 *   - redaction / decoding behavior → @hourglass-financial/api-factory-core
 *
 * Wire field names are kept verbatim (snake_case) for 1:1 fidelity with the
 * Glyph API; secret fields are typed through core's `Secret` so tokens decode
 * to `Redacted<string>` and never print.
 */
import { Secret } from "@hourglass-financial/api-factory-core";
import * as Schema from "effect/Schema";

// ---------------------------------------------------------------------------
// Documents
// ---------------------------------------------------------------------------

/** Every closed schema kind in one wire shape. */
export const DocumentCore = Schema.Struct({
  title: Schema.String,
  published: Schema.Boolean,
  revision: Schema.Number,
  kind: Schema.Literal("document"),
  state: Schema.Literals([
    "draft",
    'quoted"value',
    "line\nbreak",
    "back\\slash",
  ]),
  tags: Schema.Array(Schema.String),
  owner: Schema.Struct({ name: Schema.String, active: Schema.Boolean }),
  metadata: Schema.Record(Schema.String, Schema.String),
  selector: Schema.Union([Schema.Literal(false), Schema.Array(Schema.Number)]),
  token: Secret,
  summary: Schema.NullOr(Schema.String),
  locale: Schema.optional(Schema.NullOr(Schema.String)),
});
export interface DocumentCore extends Schema.Schema.Type<typeof DocumentCore> {}

/** A named-reference chain around a document. */
export const DocumentEnvelope = Schema.Struct({ document: DocumentCore });
export interface DocumentEnvelope extends Schema.Schema.Type<
  typeof DocumentEnvelope
> {}
