/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  NotFound,
  type Operation,
  Pagination,
  TooManyRequests,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import {
  AuditLogActionJson,
  AuditLogActionList,
  AuditLogEventCreateResponse,
  AuditLogEventDto,
  AuditLogExportJson,
  AuditLogSchemaActorDto,
  AuditLogSchemaJson,
  AuditLogSchemaList,
  AuditLogSchemaTargetDto,
  AuditLogsRetentionJson,
} from "../schemas.ts";

// ===========================================================================
// auditLogs.createEvent — POST /audit_logs/events
// ===========================================================================

export const CreateEventInput = Schema.Struct({
  organization_id: Schema.String,
  event: AuditLogEventDto,
});
export interface CreateEventInput extends Schema.Schema.Type<
  typeof CreateEventInput
> {}

const createEventErrors = [
  BadRequest,
  NotFound,
  TooManyRequests,
  UnprocessableEntity,
] as const;

const createEventOp: Operation<
  typeof CreateEventInput,
  typeof AuditLogEventCreateResponse,
  typeof createEventErrors
> = {
  id: "auditLogs.createEvent",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/audit_logs/events",
  pathParams: [],
  queryParams: [],
  input: CreateEventInput,
  output: AuditLogEventCreateResponse,
  errors: createEventErrors,
};

/**
 * Emit an Audit Logs event for an organization. The endpoint's
 * `idempotency-key` header is not yet modeled by this client (header
 * parameters are unsupported); retried calls are not deduplicated.
 */
export const createEvent = (
  input: CreateEventInput,
): Effect.Effect<
  AuditLogEventCreateResponse,
  WorkosError<typeof createEventErrors>,
  WorkosClient
> => run(createEventOp, input);

// ===========================================================================
// auditLogs.createExport — POST /audit_logs/exports
// ===========================================================================

export const CreateExportInput = Schema.Struct({
  organization_id: Schema.String,
  range_start: Schema.String,
  range_end: Schema.String,
  actions: Schema.optional(Schema.Array(Schema.String)),
  actors: Schema.optional(Schema.Array(Schema.String)),
  actor_names: Schema.optional(Schema.Array(Schema.String)),
  actor_ids: Schema.optional(Schema.Array(Schema.String)),
  targets: Schema.optional(Schema.Array(Schema.String)),
});
export interface CreateExportInput extends Schema.Schema.Type<
  typeof CreateExportInput
> {}

const createExportErrors = [BadRequest] as const;

const createExportOp: Operation<
  typeof CreateExportInput,
  typeof AuditLogExportJson,
  typeof createExportErrors
> = {
  id: "auditLogs.createExport",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/audit_logs/exports",
  pathParams: [],
  queryParams: [],
  input: CreateExportInput,
  output: AuditLogExportJson,
  errors: createExportErrors,
};

/** Create an Audit Log Export. Exports are scoped to a single organization within a specified date range. */
export const createExport = (
  input: CreateExportInput,
): Effect.Effect<
  AuditLogExportJson,
  WorkosError<typeof createExportErrors>,
  WorkosClient
> => run(createExportOp, input);

// ===========================================================================
// auditLogs.createSchema — POST /audit_logs/actions/{actionName}/schemas
// ===========================================================================

export const CreateSchemaInput = Schema.Struct({
  actionName: Schema.String,
  actor: Schema.optional(AuditLogSchemaActorDto),
  targets: Schema.Array(AuditLogSchemaTargetDto),
  metadata: Schema.optional(Schema.Record(Schema.String, Schema.Json)),
});
export interface CreateSchemaInput extends Schema.Schema.Type<
  typeof CreateSchemaInput
> {}

const createSchemaErrors = [UnprocessableEntity] as const;

const createSchemaOp: Operation<
  typeof CreateSchemaInput,
  typeof AuditLogSchemaJson,
  typeof createSchemaErrors
> = {
  id: "auditLogs.createSchema",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/audit_logs/actions/{actionName}/schemas",
  pathParams: ["actionName"],
  queryParams: [],
  input: CreateSchemaInput,
  output: AuditLogSchemaJson,
  errors: createSchemaErrors,
};

/** Creates a new Audit Log schema used to validate the payload of incoming Audit Log Events. If the `action` does not exist, it will also be created. */
export const createSchema = (
  input: CreateSchemaInput,
): Effect.Effect<
  AuditLogSchemaJson,
  WorkosError<typeof createSchemaErrors>,
  WorkosClient
> => run(createSchemaOp, input);

// ===========================================================================
// auditLogs.getExport — GET /audit_logs/exports/{auditLogExportId}
// ===========================================================================

export const GetExportInput = Schema.Struct({
  auditLogExportId: Schema.String,
});
export interface GetExportInput extends Schema.Schema.Type<
  typeof GetExportInput
> {}

const getExportErrors = [NotFound] as const;

const getExportOp: Operation<
  typeof GetExportInput,
  typeof AuditLogExportJson,
  typeof getExportErrors
> = {
  id: "auditLogs.getExport",
  method: "GET",
  retry: "transient",
  pathTemplate: "/audit_logs/exports/{auditLogExportId}",
  pathParams: ["auditLogExportId"],
  queryParams: [],
  input: GetExportInput,
  output: AuditLogExportJson,
  errors: getExportErrors,
};

/** Get an Audit Log Export. The URL will expire after 10 minutes. If the export is needed again at a later time, refetching the export will regenerate the URL. */
export const getExport = (
  input: GetExportInput,
): Effect.Effect<
  AuditLogExportJson,
  WorkosError<typeof getExportErrors>,
  WorkosClient
> => run(getExportOp, input);

// ===========================================================================
// auditLogs.getRetention — GET /organizations/{id}/audit_logs_retention
// ===========================================================================

export const GetRetentionInput = Schema.Struct({
  id: Schema.String,
});
export interface GetRetentionInput extends Schema.Schema.Type<
  typeof GetRetentionInput
> {}

const getRetentionErrors = [NotFound] as const;

const getRetentionOp: Operation<
  typeof GetRetentionInput,
  typeof AuditLogsRetentionJson,
  typeof getRetentionErrors
> = {
  id: "auditLogs.getRetention",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organizations/{id}/audit_logs_retention",
  pathParams: ["id"],
  queryParams: [],
  input: GetRetentionInput,
  output: AuditLogsRetentionJson,
  errors: getRetentionErrors,
};

/** Get the configured event retention period for the given Organization. */
export const getRetention = (
  input: GetRetentionInput,
): Effect.Effect<
  AuditLogsRetentionJson,
  WorkosError<typeof getRetentionErrors>,
  WorkosClient
> => run(getRetentionOp, input);

// ===========================================================================
// auditLogs.listActions — GET /audit_logs/actions (cursor paginated)
// ===========================================================================

export const ListActionsInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
});
export interface ListActionsInput extends Schema.Schema.Type<
  typeof ListActionsInput
> {}

const listActionsErrors = [NotFound, UnprocessableEntity] as const;

const listActionsOp: Operation<
  typeof ListActionsInput,
  typeof AuditLogActionList,
  typeof listActionsErrors
> = {
  id: "auditLogs.listActions",
  method: "GET",
  retry: "transient",
  pathTemplate: "/audit_logs/actions",
  pathParams: [],
  queryParams: ["before", "after", "limit", "order"],
  input: ListActionsInput,
  output: AuditLogActionList,
  errors: listActionsErrors,
};

/** Get a list of all Audit Log actions in the current environment. */
export const listActions = (
  input: ListActionsInput = {},
): Effect.Effect<
  AuditLogActionList,
  WorkosError<typeof listActionsErrors>,
  WorkosClient
> => run(listActionsOp, input);

const listActionsPagination: Pagination.CursorPagination<
  ListActionsInput,
  AuditLogActionList,
  AuditLogActionJson
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of audit logs, following the `after` cursor. */
export const listActionsPages = (
  input: ListActionsInput = {},
): Stream.Stream<
  AuditLogActionList,
  WorkosError<typeof listActionsErrors>,
  WorkosClient
> => Pagination.pages(listActions, input, listActionsPagination);

/** Stream every audit log action json across every page. */
export const listActionsItems = (
  input: ListActionsInput = {},
): Stream.Stream<
  AuditLogActionJson,
  WorkosError<typeof listActionsErrors>,
  WorkosClient
> => Pagination.items(listActions, input, listActionsPagination);

// ===========================================================================
// auditLogs.listSchemas — GET /audit_logs/actions/{actionName}/schemas (cursor paginated)
// ===========================================================================

export const ListSchemasInput = Schema.Struct({
  actionName: Schema.String,
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
});
export interface ListSchemasInput extends Schema.Schema.Type<
  typeof ListSchemasInput
> {}

const listSchemasErrors = [NotFound, UnprocessableEntity] as const;

const listSchemasOp: Operation<
  typeof ListSchemasInput,
  typeof AuditLogSchemaList,
  typeof listSchemasErrors
> = {
  id: "auditLogs.listSchemas",
  method: "GET",
  retry: "transient",
  pathTemplate: "/audit_logs/actions/{actionName}/schemas",
  pathParams: ["actionName"],
  queryParams: ["before", "after", "limit", "order"],
  input: ListSchemasInput,
  output: AuditLogSchemaList,
  errors: listSchemasErrors,
};

/** Get a list of all schemas for the Audit Logs action identified by `:name`. */
export const listSchemas = (
  input: ListSchemasInput,
): Effect.Effect<
  AuditLogSchemaList,
  WorkosError<typeof listSchemasErrors>,
  WorkosClient
> => run(listSchemasOp, input);

const listSchemasPagination: Pagination.CursorPagination<
  ListSchemasInput,
  AuditLogSchemaList,
  AuditLogSchemaJson
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of audit logs, following the `after` cursor. */
export const listSchemasPages = (
  input: ListSchemasInput,
): Stream.Stream<
  AuditLogSchemaList,
  WorkosError<typeof listSchemasErrors>,
  WorkosClient
> => Pagination.pages(listSchemas, input, listSchemasPagination);

/** Stream every audit log schema json across every page. */
export const listSchemasItems = (
  input: ListSchemasInput,
): Stream.Stream<
  AuditLogSchemaJson,
  WorkosError<typeof listSchemasErrors>,
  WorkosClient
> => Pagination.items(listSchemas, input, listSchemasPagination);

// ===========================================================================
// auditLogs.setRetention — PUT /organizations/{id}/audit_logs_retention
// ===========================================================================

export const SetRetentionInput = Schema.Struct({
  id: Schema.String,
  retention_period_in_days: Schema.Number,
});
export interface SetRetentionInput extends Schema.Schema.Type<
  typeof SetRetentionInput
> {}

const setRetentionErrors = [NotFound, UnprocessableEntity] as const;

const setRetentionOp: Operation<
  typeof SetRetentionInput,
  typeof AuditLogsRetentionJson,
  typeof setRetentionErrors
> = {
  id: "auditLogs.setRetention",
  method: "PUT",
  retry: "throttling",
  pathTemplate: "/organizations/{id}/audit_logs_retention",
  pathParams: ["id"],
  queryParams: [],
  input: SetRetentionInput,
  output: AuditLogsRetentionJson,
  errors: setRetentionErrors,
};

/** Set the event retention period for the given Organization. */
export const setRetention = (
  input: SetRetentionInput,
): Effect.Effect<
  AuditLogsRetentionJson,
  WorkosError<typeof setRetentionErrors>,
  WorkosClient
> => run(setRetentionOp, input);
