/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  NotFound,
  type Operation,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import { ClientApiTokenResponse } from "../schemas.ts";

// ===========================================================================
// clientTokens.generate — POST /client/token
// ===========================================================================

export const GenerateClientTokenInput = Schema.Struct({
  organization_id: Schema.String,
  user_id: Schema.String,
});
export interface GenerateClientTokenInput extends Schema.Schema.Type<
  typeof GenerateClientTokenInput
> {}

const generateErrors = [BadRequest, NotFound, UnprocessableEntity] as const;

const generateOp: Operation<
  typeof GenerateClientTokenInput,
  typeof ClientApiTokenResponse,
  typeof generateErrors
> = {
  id: "clientTokens.generate",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/client/token",
  pathParams: [],
  queryParams: [],
  input: GenerateClientTokenInput,
  output: ClientApiTokenResponse,
  errors: generateErrors,
};

/** Generate a short-lived, session-bound token for the Client GraphQL API, scoped to an organization and user. */
export const generate = (
  input: GenerateClientTokenInput,
): Effect.Effect<
  ClientApiTokenResponse,
  WorkosError<typeof generateErrors>,
  WorkosClient
> => run(generateOp, input);
