/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  Forbidden,
  NotFound,
  type Operation,
  Pagination,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import { Connection, ConnectionList } from "../schemas.ts";

// ===========================================================================
// connections.delete — DELETE /connections/{id}
// ===========================================================================

export const DeleteConnectionInput = Schema.Struct({
  id: Schema.String,
});
export interface DeleteConnectionInput extends Schema.Schema.Type<
  typeof DeleteConnectionInput
> {}

const deleteErrors = [Forbidden, NotFound] as const;

const deleteOp: Operation<
  typeof DeleteConnectionInput,
  typeof Schema.Void,
  typeof deleteErrors
> = {
  id: "connections.delete",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/connections/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: DeleteConnectionInput,
  output: Schema.Void,
  errors: deleteErrors,
};

/** Permanently deletes an existing connection. It cannot be undone. */
const deleteConnection = (
  input: DeleteConnectionInput,
): Effect.Effect<void, WorkosError<typeof deleteErrors>, WorkosClient> =>
  run(deleteOp, input);

// `delete` is a reserved word as a declaration name but a legal export name;
// the rename-export keeps the public surface on the API's own verb.
export { deleteConnection as delete };

// ===========================================================================
// connections.get — GET /connections/{id}
// ===========================================================================

export const GetConnectionInput = Schema.Struct({
  id: Schema.String,
});
export interface GetConnectionInput extends Schema.Schema.Type<
  typeof GetConnectionInput
> {}

const getErrors = [Forbidden, NotFound] as const;

const getOp: Operation<
  typeof GetConnectionInput,
  typeof Connection,
  typeof getErrors
> = {
  id: "connections.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/connections/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: GetConnectionInput,
  output: Connection,
  errors: getErrors,
};

/** Get the details of an existing connection. */
export const get = (
  input: GetConnectionInput,
): Effect.Effect<Connection, WorkosError<typeof getErrors>, WorkosClient> =>
  run(getOp, input);

// ===========================================================================
// connections.list — GET /connections (cursor paginated)
// ===========================================================================

export const ListConnectionsInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
  connection_type: Schema.optional(
    Schema.Literals([
      "ADFSSAML",
      "AdpOidc",
      "AppleOAuth",
      "Auth0SAML",
      "AzureSAML",
      "BitbucketOAuth",
      "CasSAML",
      "CloudflareSAML",
      "ClassLinkSAML",
      "CleverOIDC",
      "CyberArkSAML",
      "DiscordOAuth",
      "DuoSAML",
      "EntraIdOIDC",
      "GenericOIDC",
      "GenericSAML",
      "GithubOAuth",
      "GitLabOAuth",
      "GoogleOAuth",
      "GoogleOIDC",
      "GoogleSAML",
      "IntuitOAuth",
      "JumpCloudSAML",
      "KeycloakSAML",
      "LastPassSAML",
      "LinkedInOAuth",
      "LoginGovOidc",
      "MagicLink",
      "MicrosoftOAuth",
      "MiniOrangeSAML",
      "NetIqSAML",
      "OktaOIDC",
      "OktaSAML",
      "OneLoginSAML",
      "OracleSAML",
      "PingFederateSAML",
      "PingOneSAML",
      "RipplingSAML",
      "SalesforceSAML",
      "ShibbolethGenericSAML",
      "ShibbolethSAML",
      "SimpleSamlPhpSAML",
      "SalesforceOAuth",
      "SlackOAuth",
      "VercelMarketplaceOAuth",
      "VercelOAuth",
      "VMwareSAML",
      "XeroOAuth",
    ]),
  ),
  domain: Schema.optional(Schema.String),
  organization_id: Schema.optional(Schema.String),
  search: Schema.optional(Schema.String),
});
export interface ListConnectionsInput extends Schema.Schema.Type<
  typeof ListConnectionsInput
> {}

const listErrors = [Forbidden, UnprocessableEntity] as const;

const listOp: Operation<
  typeof ListConnectionsInput,
  typeof ConnectionList,
  typeof listErrors
> = {
  id: "connections.list",
  method: "GET",
  retry: "transient",
  pathTemplate: "/connections",
  pathParams: [],
  queryParams: [
    "before",
    "after",
    "limit",
    "order",
    "connection_type",
    "domain",
    "organization_id",
    "search",
  ],
  input: ListConnectionsInput,
  output: ConnectionList,
  errors: listErrors,
};

/** Get a list of all of your existing connections matching the criteria specified. */
export const list = (
  input: ListConnectionsInput = {},
): Effect.Effect<
  ConnectionList,
  WorkosError<typeof listErrors>,
  WorkosClient
> => run(listOp, input);

const listPagination: Pagination.CursorPagination<
  ListConnectionsInput,
  ConnectionList,
  Connection
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of connections, following the `after` cursor. */
export const listPages = (
  input: ListConnectionsInput = {},
): Stream.Stream<
  ConnectionList,
  WorkosError<typeof listErrors>,
  WorkosClient
> => Pagination.pages(list, input, listPagination);

/** Stream every connection across every page. */
export const listItems = (
  input: ListConnectionsInput = {},
): Stream.Stream<Connection, WorkosError<typeof listErrors>, WorkosClient> =>
  Pagination.items(list, input, listPagination);
