/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  Forbidden,
  NotFound,
  type Operation,
  Pagination,
  TooManyRequests,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import {
  Directory,
  DirectoryGroup,
  DirectoryGroupList,
  DirectoryList,
  DirectoryUserList,
  DirectoryUserWithGroups,
} from "../schemas.ts";

// ===========================================================================
// directorySync.deleteDirectory — DELETE /directories/{id}
// ===========================================================================

export const DeleteDirectoryInput = Schema.Struct({
  id: Schema.String,
});
export interface DeleteDirectoryInput extends Schema.Schema.Type<
  typeof DeleteDirectoryInput
> {}

const deleteDirectoryErrors = [Forbidden] as const;

const deleteDirectoryOp: Operation<
  typeof DeleteDirectoryInput,
  typeof Schema.Void,
  typeof deleteDirectoryErrors
> = {
  id: "directorySync.deleteDirectory",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/directories/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: DeleteDirectoryInput,
  output: Schema.Void,
  errors: deleteDirectoryErrors,
};

/** Permanently deletes an existing directory. It cannot be undone. */
export const deleteDirectory = (
  input: DeleteDirectoryInput,
): Effect.Effect<
  void,
  WorkosError<typeof deleteDirectoryErrors>,
  WorkosClient
> => run(deleteDirectoryOp, input);

// ===========================================================================
// directorySync.getDirectory — GET /directories/{id}
// ===========================================================================

export const GetDirectoryInput = Schema.Struct({
  id: Schema.String,
});
export interface GetDirectoryInput extends Schema.Schema.Type<
  typeof GetDirectoryInput
> {}

const getDirectoryErrors = [Forbidden, NotFound] as const;

const getDirectoryOp: Operation<
  typeof GetDirectoryInput,
  typeof Directory,
  typeof getDirectoryErrors
> = {
  id: "directorySync.getDirectory",
  method: "GET",
  retry: "transient",
  pathTemplate: "/directories/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: GetDirectoryInput,
  output: Directory,
  errors: getDirectoryErrors,
};

/** Get the details of an existing directory. */
export const getDirectory = (
  input: GetDirectoryInput,
): Effect.Effect<
  Directory,
  WorkosError<typeof getDirectoryErrors>,
  WorkosClient
> => run(getDirectoryOp, input);

// ===========================================================================
// directorySync.getGroup — GET /directory_groups/{id}
// ===========================================================================

export const GetDirectoryGroupInput = Schema.Struct({
  id: Schema.String,
});
export interface GetDirectoryGroupInput extends Schema.Schema.Type<
  typeof GetDirectoryGroupInput
> {}

const getGroupErrors = [Forbidden, NotFound] as const;

const getGroupOp: Operation<
  typeof GetDirectoryGroupInput,
  typeof DirectoryGroup,
  typeof getGroupErrors
> = {
  id: "directorySync.getGroup",
  method: "GET",
  retry: "transient",
  pathTemplate: "/directory_groups/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: GetDirectoryGroupInput,
  output: DirectoryGroup,
  errors: getGroupErrors,
};

/** Get the details of an existing Directory Group. */
export const getGroup = (
  input: GetDirectoryGroupInput,
): Effect.Effect<
  DirectoryGroup,
  WorkosError<typeof getGroupErrors>,
  WorkosClient
> => run(getGroupOp, input);

// ===========================================================================
// directorySync.getUser — GET /directory_users/{id}
// ===========================================================================

export const GetDirectoryUserInput = Schema.Struct({
  id: Schema.String,
});
export interface GetDirectoryUserInput extends Schema.Schema.Type<
  typeof GetDirectoryUserInput
> {}

const getUserErrors = [Forbidden, NotFound] as const;

const getUserOp: Operation<
  typeof GetDirectoryUserInput,
  typeof DirectoryUserWithGroups,
  typeof getUserErrors
> = {
  id: "directorySync.getUser",
  method: "GET",
  retry: "transient",
  pathTemplate: "/directory_users/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: GetDirectoryUserInput,
  output: DirectoryUserWithGroups,
  errors: getUserErrors,
};

/** Get the details of an existing Directory User. */
export const getUser = (
  input: GetDirectoryUserInput,
): Effect.Effect<
  DirectoryUserWithGroups,
  WorkosError<typeof getUserErrors>,
  WorkosClient
> => run(getUserOp, input);

// ===========================================================================
// directorySync.listDirectories — GET /directories (cursor paginated)
// ===========================================================================

export const ListDirectoriesInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
  organization_id: Schema.optional(Schema.String),
  search: Schema.optional(Schema.String),
  domain: Schema.optional(Schema.String),
});
export interface ListDirectoriesInput extends Schema.Schema.Type<
  typeof ListDirectoriesInput
> {}

const listDirectoriesErrors = [Forbidden, UnprocessableEntity] as const;

const listDirectoriesOp: Operation<
  typeof ListDirectoriesInput,
  typeof DirectoryList,
  typeof listDirectoriesErrors
> = {
  id: "directorySync.listDirectories",
  method: "GET",
  retry: "transient",
  pathTemplate: "/directories",
  pathParams: [],
  queryParams: [
    "before",
    "after",
    "limit",
    "order",
    "organization_id",
    "search",
    "domain",
  ],
  input: ListDirectoriesInput,
  output: DirectoryList,
  errors: listDirectoriesErrors,
};

/** Get a list of all of your existing directories matching the criteria specified. */
export const listDirectories = (
  input: ListDirectoriesInput = {},
): Effect.Effect<
  DirectoryList,
  WorkosError<typeof listDirectoriesErrors>,
  WorkosClient
> => run(listDirectoriesOp, input);

const listDirectoriesPagination: Pagination.CursorPagination<
  ListDirectoriesInput,
  DirectoryList,
  Directory
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of directory sync, following the `after` cursor. */
export const listDirectoriesPages = (
  input: ListDirectoriesInput = {},
): Stream.Stream<
  DirectoryList,
  WorkosError<typeof listDirectoriesErrors>,
  WorkosClient
> => Pagination.pages(listDirectories, input, listDirectoriesPagination);

/** Stream every directory across every page. */
export const listDirectoriesItems = (
  input: ListDirectoriesInput = {},
): Stream.Stream<
  Directory,
  WorkosError<typeof listDirectoriesErrors>,
  WorkosClient
> => Pagination.items(listDirectories, input, listDirectoriesPagination);

// ===========================================================================
// directorySync.listGroups — GET /directory_groups (cursor paginated)
// ===========================================================================

export const ListDirectoryGroupsInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
  directory: Schema.optional(Schema.String),
  user: Schema.optional(Schema.String),
});
export interface ListDirectoryGroupsInput extends Schema.Schema.Type<
  typeof ListDirectoryGroupsInput
> {}

const listGroupsErrors = [Forbidden, NotFound, UnprocessableEntity] as const;

const listGroupsOp: Operation<
  typeof ListDirectoryGroupsInput,
  typeof DirectoryGroupList,
  typeof listGroupsErrors
> = {
  id: "directorySync.listGroups",
  method: "GET",
  retry: "transient",
  pathTemplate: "/directory_groups",
  pathParams: [],
  queryParams: ["before", "after", "limit", "order", "directory", "user"],
  input: ListDirectoryGroupsInput,
  output: DirectoryGroupList,
  errors: listGroupsErrors,
};

/** Get a list of all of existing directory groups matching the criteria specified. */
export const listGroups = (
  input: ListDirectoryGroupsInput = {},
): Effect.Effect<
  DirectoryGroupList,
  WorkosError<typeof listGroupsErrors>,
  WorkosClient
> => run(listGroupsOp, input);

const listGroupsPagination: Pagination.CursorPagination<
  ListDirectoryGroupsInput,
  DirectoryGroupList,
  DirectoryGroup
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of directory sync, following the `after` cursor. */
export const listGroupsPages = (
  input: ListDirectoryGroupsInput = {},
): Stream.Stream<
  DirectoryGroupList,
  WorkosError<typeof listGroupsErrors>,
  WorkosClient
> => Pagination.pages(listGroups, input, listGroupsPagination);

/** Stream every directory group across every page. */
export const listGroupsItems = (
  input: ListDirectoryGroupsInput = {},
): Stream.Stream<
  DirectoryGroup,
  WorkosError<typeof listGroupsErrors>,
  WorkosClient
> => Pagination.items(listGroups, input, listGroupsPagination);

// ===========================================================================
// directorySync.listUsers — GET /directory_users (cursor paginated)
// ===========================================================================

export const ListDirectoryUsersInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
  directory: Schema.optional(Schema.String),
  group: Schema.optional(Schema.String),
  idp_id: Schema.optional(Schema.String),
  email: Schema.optional(Schema.String),
});
export interface ListDirectoryUsersInput extends Schema.Schema.Type<
  typeof ListDirectoryUsersInput
> {}

const listUsersErrors = [
  Forbidden,
  NotFound,
  TooManyRequests,
  UnprocessableEntity,
] as const;

const listUsersOp: Operation<
  typeof ListDirectoryUsersInput,
  typeof DirectoryUserList,
  typeof listUsersErrors
> = {
  id: "directorySync.listUsers",
  method: "GET",
  retry: "transient",
  pathTemplate: "/directory_users",
  pathParams: [],
  queryParams: [
    "before",
    "after",
    "limit",
    "order",
    "directory",
    "group",
    "idp_id",
    "email",
  ],
  input: ListDirectoryUsersInput,
  output: DirectoryUserList,
  errors: listUsersErrors,
};

/** Get a list of all of existing Directory Users matching the criteria specified. */
export const listUsers = (
  input: ListDirectoryUsersInput = {},
): Effect.Effect<
  DirectoryUserList,
  WorkosError<typeof listUsersErrors>,
  WorkosClient
> => run(listUsersOp, input);

const listUsersPagination: Pagination.CursorPagination<
  ListDirectoryUsersInput,
  DirectoryUserList,
  DirectoryUserWithGroups
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of directory sync, following the `after` cursor. */
export const listUsersPages = (
  input: ListDirectoryUsersInput = {},
): Stream.Stream<
  DirectoryUserList,
  WorkosError<typeof listUsersErrors>,
  WorkosClient
> => Pagination.pages(listUsers, input, listUsersPagination);

/** Stream every directory user with groups across every page. */
export const listUsersItems = (
  input: ListDirectoryUsersInput = {},
): Stream.Stream<
  DirectoryUserWithGroups,
  WorkosError<typeof listUsersErrors>,
  WorkosClient
> => Pagination.items(listUsers, input, listUsersPagination);
