/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  type Operation,
  Pagination,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import { EventList, EventSchema } from "../schemas.ts";

// ===========================================================================
// events.list — GET /events (cursor paginated)
// ===========================================================================

export const ListEventsInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
  events: Schema.optional(Schema.Array(Schema.String)),
  range_start: Schema.optional(Schema.String),
  range_end: Schema.optional(Schema.String),
  organization_id: Schema.optional(Schema.String),
});
export interface ListEventsInput extends Schema.Schema.Type<
  typeof ListEventsInput
> {}

const listErrors = [BadRequest, UnprocessableEntity] as const;

const listOp: Operation<
  typeof ListEventsInput,
  typeof EventList,
  typeof listErrors
> = {
  id: "events.list",
  method: "GET",
  retry: "transient",
  pathTemplate: "/events",
  pathParams: [],
  queryParams: [
    "before",
    "after",
    "limit",
    "order",
    "events",
    "range_start",
    "range_end",
    "organization_id",
  ],
  input: ListEventsInput,
  output: EventList,
  errors: listErrors,
};

/** List events for the current environment. */
export const list = (
  input: ListEventsInput = {},
): Effect.Effect<EventList, WorkosError<typeof listErrors>, WorkosClient> =>
  run(listOp, input);

const listPagination: Pagination.CursorPagination<
  ListEventsInput,
  EventList,
  EventSchema
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of events, following the `after` cursor. */
export const listPages = (
  input: ListEventsInput = {},
): Stream.Stream<EventList, WorkosError<typeof listErrors>, WorkosClient> =>
  Pagination.pages(list, input, listPagination);

/** Stream every event schema across every page. */
export const listItems = (
  input: ListEventsInput = {},
): Stream.Stream<EventSchema, WorkosError<typeof listErrors>, WorkosClient> =>
  Pagination.items(list, input, listPagination);
