/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  Forbidden,
  NotFound,
  type Operation,
  Pagination,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import {
  FeatureFlagDisableResponse,
  FeatureFlagEnableResponse,
  Flag,
  FlagList,
} from "../schemas.ts";

// ===========================================================================
// featureFlags.createTarget — POST /feature-flags/{slug}/targets/{resourceId}
// ===========================================================================

export const CreateFlagTargetInput = Schema.Struct({
  resourceId: Schema.String,
  slug: Schema.String,
});
export interface CreateFlagTargetInput extends Schema.Schema.Type<
  typeof CreateFlagTargetInput
> {}

const createTargetErrors = [BadRequest, Forbidden, NotFound] as const;

const createTargetOp: Operation<
  typeof CreateFlagTargetInput,
  typeof Schema.Void,
  typeof createTargetErrors
> = {
  id: "featureFlags.createTarget",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/feature-flags/{slug}/targets/{resourceId}",
  pathParams: ["resourceId", "slug"],
  queryParams: [],
  input: CreateFlagTargetInput,
  output: Schema.Void,
  errors: createTargetErrors,
};

/** Enables a feature flag for a specific target in the current environment. Currently, supported targets include users and organizations. */
export const createTarget = (
  input: CreateFlagTargetInput,
): Effect.Effect<void, WorkosError<typeof createTargetErrors>, WorkosClient> =>
  run(createTargetOp, input);

// ===========================================================================
// featureFlags.deleteTarget — DELETE /feature-flags/{slug}/targets/{resourceId}
// ===========================================================================

export const DeleteFlagTargetInput = Schema.Struct({
  resourceId: Schema.String,
  slug: Schema.String,
});
export interface DeleteFlagTargetInput extends Schema.Schema.Type<
  typeof DeleteFlagTargetInput
> {}

const deleteTargetErrors = [BadRequest, Forbidden, NotFound] as const;

const deleteTargetOp: Operation<
  typeof DeleteFlagTargetInput,
  typeof Schema.Void,
  typeof deleteTargetErrors
> = {
  id: "featureFlags.deleteTarget",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/feature-flags/{slug}/targets/{resourceId}",
  pathParams: ["resourceId", "slug"],
  queryParams: [],
  input: DeleteFlagTargetInput,
  output: Schema.Void,
  errors: deleteTargetErrors,
};

/** Removes a target from the feature flag's target list in the current environment. Currently, supported targets include users and organizations. */
export const deleteTarget = (
  input: DeleteFlagTargetInput,
): Effect.Effect<void, WorkosError<typeof deleteTargetErrors>, WorkosClient> =>
  run(deleteTargetOp, input);

// ===========================================================================
// featureFlags.disable — PUT /feature-flags/{slug}/disable
// ===========================================================================

export const DisableFeatureFlagInput = Schema.Struct({
  slug: Schema.String,
});
export interface DisableFeatureFlagInput extends Schema.Schema.Type<
  typeof DisableFeatureFlagInput
> {}

const disableErrors = [NotFound] as const;

const disableOp: Operation<
  typeof DisableFeatureFlagInput,
  typeof FeatureFlagDisableResponse,
  typeof disableErrors
> = {
  id: "featureFlags.disable",
  method: "PUT",
  retry: "throttling",
  pathTemplate: "/feature-flags/{slug}/disable",
  pathParams: ["slug"],
  queryParams: [],
  input: DisableFeatureFlagInput,
  output: FeatureFlagDisableResponse,
  errors: disableErrors,
};

/** Disables a feature flag in the current environment. */
export const disable = (
  input: DisableFeatureFlagInput,
): Effect.Effect<
  FeatureFlagDisableResponse,
  WorkosError<typeof disableErrors>,
  WorkosClient
> => run(disableOp, input);

// ===========================================================================
// featureFlags.enable — PUT /feature-flags/{slug}/enable
// ===========================================================================

export const EnableFeatureFlagInput = Schema.Struct({
  slug: Schema.String,
});
export interface EnableFeatureFlagInput extends Schema.Schema.Type<
  typeof EnableFeatureFlagInput
> {}

const enableErrors = [NotFound] as const;

const enableOp: Operation<
  typeof EnableFeatureFlagInput,
  typeof FeatureFlagEnableResponse,
  typeof enableErrors
> = {
  id: "featureFlags.enable",
  method: "PUT",
  retry: "throttling",
  pathTemplate: "/feature-flags/{slug}/enable",
  pathParams: ["slug"],
  queryParams: [],
  input: EnableFeatureFlagInput,
  output: FeatureFlagEnableResponse,
  errors: enableErrors,
};

/** Enables a feature flag in the current environment. */
export const enable = (
  input: EnableFeatureFlagInput,
): Effect.Effect<
  FeatureFlagEnableResponse,
  WorkosError<typeof enableErrors>,
  WorkosClient
> => run(enableOp, input);

// ===========================================================================
// featureFlags.get — GET /feature-flags/{slug}
// ===========================================================================

export const GetFeatureFlagInput = Schema.Struct({
  slug: Schema.String,
});
export interface GetFeatureFlagInput extends Schema.Schema.Type<
  typeof GetFeatureFlagInput
> {}

const getErrors = [NotFound] as const;

const getOp: Operation<
  typeof GetFeatureFlagInput,
  typeof Flag,
  typeof getErrors
> = {
  id: "featureFlags.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/feature-flags/{slug}",
  pathParams: ["slug"],
  queryParams: [],
  input: GetFeatureFlagInput,
  output: Flag,
  errors: getErrors,
};

/** Get the details of an existing feature flag by its slug. */
export const get = (
  input: GetFeatureFlagInput,
): Effect.Effect<Flag, WorkosError<typeof getErrors>, WorkosClient> =>
  run(getOp, input);

// ===========================================================================
// featureFlags.list — GET /feature-flags (cursor paginated)
// ===========================================================================

export const ListFeatureFlagsInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
});
export interface ListFeatureFlagsInput extends Schema.Schema.Type<
  typeof ListFeatureFlagsInput
> {}

const listErrors = [BadRequest, NotFound, UnprocessableEntity] as const;

const listOp: Operation<
  typeof ListFeatureFlagsInput,
  typeof FlagList,
  typeof listErrors
> = {
  id: "featureFlags.list",
  method: "GET",
  retry: "transient",
  pathTemplate: "/feature-flags",
  pathParams: [],
  queryParams: ["before", "after", "limit", "order"],
  input: ListFeatureFlagsInput,
  output: FlagList,
  errors: listErrors,
};

/** Get a list of all of your existing feature flags matching the criteria specified. */
export const list = (
  input: ListFeatureFlagsInput = {},
): Effect.Effect<FlagList, WorkosError<typeof listErrors>, WorkosClient> =>
  run(listOp, input);

const listPagination: Pagination.CursorPagination<
  ListFeatureFlagsInput,
  FlagList,
  Flag
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of feature flags, following the `after` cursor. */
export const listPages = (
  input: ListFeatureFlagsInput = {},
): Stream.Stream<FlagList, WorkosError<typeof listErrors>, WorkosClient> =>
  Pagination.pages(list, input, listPagination);

/** Stream every flag across every page. */
export const listItems = (
  input: ListFeatureFlagsInput = {},
): Stream.Stream<Flag, WorkosError<typeof listErrors>, WorkosClient> =>
  Pagination.items(list, input, listPagination);

// ===========================================================================
// featureFlags.listForOrganization — GET /organizations/{organizationId}/feature-flags (cursor paginated)
// ===========================================================================

export const ListOrganizationFeatureFlagsInput = Schema.Struct({
  organizationId: Schema.String,
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
});
export interface ListOrganizationFeatureFlagsInput extends Schema.Schema.Type<
  typeof ListOrganizationFeatureFlagsInput
> {}

const listForOrganizationErrors = [NotFound] as const;

const listForOrganizationOp: Operation<
  typeof ListOrganizationFeatureFlagsInput,
  typeof FlagList,
  typeof listForOrganizationErrors
> = {
  id: "featureFlags.listForOrganization",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organizations/{organizationId}/feature-flags",
  pathParams: ["organizationId"],
  queryParams: ["before", "after", "limit", "order"],
  input: ListOrganizationFeatureFlagsInput,
  output: FlagList,
  errors: listForOrganizationErrors,
};

/** Get a list of all enabled feature flags for an organization. */
export const listForOrganization = (
  input: ListOrganizationFeatureFlagsInput,
): Effect.Effect<
  FlagList,
  WorkosError<typeof listForOrganizationErrors>,
  WorkosClient
> => run(listForOrganizationOp, input);

const listForOrganizationPagination: Pagination.CursorPagination<
  ListOrganizationFeatureFlagsInput,
  FlagList,
  Flag
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of feature flags, following the `after` cursor. */
export const listForOrganizationPages = (
  input: ListOrganizationFeatureFlagsInput,
): Stream.Stream<
  FlagList,
  WorkosError<typeof listForOrganizationErrors>,
  WorkosClient
> =>
  Pagination.pages(listForOrganization, input, listForOrganizationPagination);

/** Stream every flag across every page. */
export const listForOrganizationItems = (
  input: ListOrganizationFeatureFlagsInput,
): Stream.Stream<
  Flag,
  WorkosError<typeof listForOrganizationErrors>,
  WorkosClient
> =>
  Pagination.items(listForOrganization, input, listForOrganizationPagination);
