/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  Forbidden,
  NotFound,
  type Operation,
  Pagination,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import {
  Group,
  GroupList,
  OrganizationMembershipBaseList,
  OrganizationMembershipBaseListItem,
} from "../schemas.ts";

// ===========================================================================
// groups.addMember — POST /organizations/{organizationId}/groups/{groupId}/organization-memberships
// ===========================================================================

export const AddGroupMemberInput = Schema.Struct({
  organizationId: Schema.String,
  groupId: Schema.String,
  organization_membership_id: Schema.String,
});
export interface AddGroupMemberInput extends Schema.Schema.Type<
  typeof AddGroupMemberInput
> {}

const addMemberErrors = [
  BadRequest,
  Forbidden,
  NotFound,
  UnprocessableEntity,
] as const;

const addMemberOp: Operation<
  typeof AddGroupMemberInput,
  typeof Group,
  typeof addMemberErrors
> = {
  id: "groups.addMember",
  method: "POST",
  retry: "throttling",
  pathTemplate:
    "/organizations/{organizationId}/groups/{groupId}/organization-memberships",
  pathParams: ["organizationId", "groupId"],
  queryParams: [],
  input: AddGroupMemberInput,
  output: Group,
  errors: addMemberErrors,
};

/** Add an organization membership to a group. */
export const addMember = (
  input: AddGroupMemberInput,
): Effect.Effect<Group, WorkosError<typeof addMemberErrors>, WorkosClient> =>
  run(addMemberOp, input);

// ===========================================================================
// groups.create — POST /organizations/{organizationId}/groups
// ===========================================================================

export const CreateGroupInput = Schema.Struct({
  organizationId: Schema.String,
  name: Schema.String,
  description: Schema.optional(Schema.NullOr(Schema.String)),
});
export interface CreateGroupInput extends Schema.Schema.Type<
  typeof CreateGroupInput
> {}

const createErrors = [
  BadRequest,
  Forbidden,
  NotFound,
  UnprocessableEntity,
] as const;

const createOp: Operation<
  typeof CreateGroupInput,
  typeof Group,
  typeof createErrors
> = {
  id: "groups.create",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/organizations/{organizationId}/groups",
  pathParams: ["organizationId"],
  queryParams: [],
  input: CreateGroupInput,
  output: Group,
  errors: createErrors,
};

/** Create a new group within an organization. */
export const create = (
  input: CreateGroupInput,
): Effect.Effect<Group, WorkosError<typeof createErrors>, WorkosClient> =>
  run(createOp, input);

// ===========================================================================
// groups.delete — DELETE /organizations/{organizationId}/groups/{groupId}
// ===========================================================================

export const DeleteGroupInput = Schema.Struct({
  organizationId: Schema.String,
  groupId: Schema.String,
});
export interface DeleteGroupInput extends Schema.Schema.Type<
  typeof DeleteGroupInput
> {}

const deleteErrors = [Forbidden, NotFound] as const;

const deleteOp: Operation<
  typeof DeleteGroupInput,
  typeof Schema.Void,
  typeof deleteErrors
> = {
  id: "groups.delete",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/organizations/{organizationId}/groups/{groupId}",
  pathParams: ["organizationId", "groupId"],
  queryParams: [],
  input: DeleteGroupInput,
  output: Schema.Void,
  errors: deleteErrors,
};

/** Delete a group from an organization. */
const deleteGroup = (
  input: DeleteGroupInput,
): Effect.Effect<void, WorkosError<typeof deleteErrors>, WorkosClient> =>
  run(deleteOp, input);

// `delete` is a reserved word as a declaration name but a legal export name;
// the rename-export keeps the public surface on the API's own verb.
export { deleteGroup as delete };

// ===========================================================================
// groups.get — GET /organizations/{organizationId}/groups/{groupId}
// ===========================================================================

export const GetGroupInput = Schema.Struct({
  organizationId: Schema.String,
  groupId: Schema.String,
});
export interface GetGroupInput extends Schema.Schema.Type<
  typeof GetGroupInput
> {}

const getErrors = [Forbidden, NotFound] as const;

const getOp: Operation<typeof GetGroupInput, typeof Group, typeof getErrors> = {
  id: "groups.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organizations/{organizationId}/groups/{groupId}",
  pathParams: ["organizationId", "groupId"],
  queryParams: [],
  input: GetGroupInput,
  output: Group,
  errors: getErrors,
};

/** Retrieve a group by its ID within an organization. */
export const get = (
  input: GetGroupInput,
): Effect.Effect<Group, WorkosError<typeof getErrors>, WorkosClient> =>
  run(getOp, input);

// ===========================================================================
// groups.list — GET /organizations/{organizationId}/groups (cursor paginated)
// ===========================================================================

export const ListGroupsInput = Schema.Struct({
  organizationId: Schema.String,
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
});
export interface ListGroupsInput extends Schema.Schema.Type<
  typeof ListGroupsInput
> {}

const listErrors = [Forbidden, NotFound] as const;

const listOp: Operation<
  typeof ListGroupsInput,
  typeof GroupList,
  typeof listErrors
> = {
  id: "groups.list",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organizations/{organizationId}/groups",
  pathParams: ["organizationId"],
  queryParams: ["before", "after", "limit", "order"],
  input: ListGroupsInput,
  output: GroupList,
  errors: listErrors,
};

/** Get a paginated list of groups within an organization. */
export const list = (
  input: ListGroupsInput,
): Effect.Effect<GroupList, WorkosError<typeof listErrors>, WorkosClient> =>
  run(listOp, input);

const listPagination: Pagination.CursorPagination<
  ListGroupsInput,
  GroupList,
  Group
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of groups, following the `after` cursor. */
export const listPages = (
  input: ListGroupsInput,
): Stream.Stream<GroupList, WorkosError<typeof listErrors>, WorkosClient> =>
  Pagination.pages(list, input, listPagination);

/** Stream every group across every page. */
export const listItems = (
  input: ListGroupsInput,
): Stream.Stream<Group, WorkosError<typeof listErrors>, WorkosClient> =>
  Pagination.items(list, input, listPagination);

// ===========================================================================
// groups.listMembers — GET /organizations/{organizationId}/groups/{groupId}/organization-memberships (cursor paginated)
// ===========================================================================

export const ListGroupMembersInput = Schema.Struct({
  organizationId: Schema.String,
  groupId: Schema.String,
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
});
export interface ListGroupMembersInput extends Schema.Schema.Type<
  typeof ListGroupMembersInput
> {}

const listMembersErrors = [Forbidden, NotFound] as const;

const listMembersOp: Operation<
  typeof ListGroupMembersInput,
  typeof OrganizationMembershipBaseList,
  typeof listMembersErrors
> = {
  id: "groups.listMembers",
  method: "GET",
  retry: "transient",
  pathTemplate:
    "/organizations/{organizationId}/groups/{groupId}/organization-memberships",
  pathParams: ["organizationId", "groupId"],
  queryParams: ["before", "after", "limit", "order"],
  input: ListGroupMembersInput,
  output: OrganizationMembershipBaseList,
  errors: listMembersErrors,
};

/** Get a list of organization memberships in a group. */
export const listMembers = (
  input: ListGroupMembersInput,
): Effect.Effect<
  OrganizationMembershipBaseList,
  WorkosError<typeof listMembersErrors>,
  WorkosClient
> => run(listMembersOp, input);

const listMembersPagination: Pagination.CursorPagination<
  ListGroupMembersInput,
  OrganizationMembershipBaseList,
  OrganizationMembershipBaseListItem
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of groups, following the `after` cursor. */
export const listMembersPages = (
  input: ListGroupMembersInput,
): Stream.Stream<
  OrganizationMembershipBaseList,
  WorkosError<typeof listMembersErrors>,
  WorkosClient
> => Pagination.pages(listMembers, input, listMembersPagination);

/** Stream every organization membership base list item across every page. */
export const listMembersItems = (
  input: ListGroupMembersInput,
): Stream.Stream<
  OrganizationMembershipBaseListItem,
  WorkosError<typeof listMembersErrors>,
  WorkosClient
> => Pagination.items(listMembers, input, listMembersPagination);

// ===========================================================================
// groups.removeMember — DELETE /organizations/{organizationId}/groups/{groupId}/organization-memberships/{omId}
// ===========================================================================

export const RemoveGroupMemberInput = Schema.Struct({
  organizationId: Schema.String,
  groupId: Schema.String,
  omId: Schema.String,
});
export interface RemoveGroupMemberInput extends Schema.Schema.Type<
  typeof RemoveGroupMemberInput
> {}

const removeMemberErrors = [Forbidden, NotFound] as const;

const removeMemberOp: Operation<
  typeof RemoveGroupMemberInput,
  typeof Schema.Void,
  typeof removeMemberErrors
> = {
  id: "groups.removeMember",
  method: "DELETE",
  retry: "throttling",
  pathTemplate:
    "/organizations/{organizationId}/groups/{groupId}/organization-memberships/{omId}",
  pathParams: ["organizationId", "groupId", "omId"],
  queryParams: [],
  input: RemoveGroupMemberInput,
  output: Schema.Void,
  errors: removeMemberErrors,
};

/** Remove an organization membership from a group. */
export const removeMember = (
  input: RemoveGroupMemberInput,
): Effect.Effect<void, WorkosError<typeof removeMemberErrors>, WorkosClient> =>
  run(removeMemberOp, input);

// ===========================================================================
// groups.update — PATCH /organizations/{organizationId}/groups/{groupId}
// ===========================================================================

export const UpdateGroupInput = Schema.Struct({
  organizationId: Schema.String,
  groupId: Schema.String,
  name: Schema.optional(Schema.String),
  description: Schema.optional(Schema.NullOr(Schema.String)),
});
export interface UpdateGroupInput extends Schema.Schema.Type<
  typeof UpdateGroupInput
> {}

const updateErrors = [
  BadRequest,
  Forbidden,
  NotFound,
  UnprocessableEntity,
] as const;

const updateOp: Operation<
  typeof UpdateGroupInput,
  typeof Group,
  typeof updateErrors
> = {
  id: "groups.update",
  method: "PATCH",
  retry: "throttling",
  pathTemplate: "/organizations/{organizationId}/groups/{groupId}",
  pathParams: ["organizationId", "groupId"],
  queryParams: [],
  input: UpdateGroupInput,
  output: Group,
  errors: updateErrors,
};

/** Update an existing group. Only the fields provided in the request body will be updated. */
export const update = (
  input: UpdateGroupInput,
): Effect.Effect<Group, WorkosError<typeof updateErrors>, WorkosClient> =>
  run(updateOp, input);
