/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  Conflict,
  Forbidden,
  NotFound,
  type Operation,
  Pagination,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import {
  ExternalIdAlreadyUsed,
  InvalidMetadata,
  StripeCustomerIdAlreadyUsed,
} from "../errors.ts";
import {
  AuditLogConfiguration,
  Organization,
  OrganizationAuthorizedApplication,
  OrganizationAuthorizedConnectApplicationList,
  OrganizationDomainDataDto,
  OrganizationList,
} from "../schemas.ts";

// ===========================================================================
// organizations.create — POST /organizations
// ===========================================================================

export const CreateOrganizationInput = Schema.Struct({
  name: Schema.String,
  allow_profiles_outside_organization: Schema.optional(Schema.Boolean),
  domains: Schema.optional(Schema.Array(Schema.String)),
  domain_data: Schema.optional(Schema.Array(OrganizationDomainDataDto)),
  metadata: Schema.optional(
    Schema.NullOr(Schema.Record(Schema.String, Schema.String)),
  ),
  external_id: Schema.optional(Schema.NullOr(Schema.String)),
});
export interface CreateOrganizationInput extends Schema.Schema.Type<
  typeof CreateOrganizationInput
> {}

const createErrors = [
  Conflict,
  ExternalIdAlreadyUsed,
  InvalidMetadata,
  UnprocessableEntity,
] as const;

const createOp: Operation<
  typeof CreateOrganizationInput,
  typeof Organization,
  typeof createErrors
> = {
  id: "organizations.create",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/organizations",
  pathParams: [],
  queryParams: [],
  input: CreateOrganizationInput,
  output: Organization,
  errors: createErrors,
};

/** Create an organization in the current environment. */
export const create = (
  input: CreateOrganizationInput,
): Effect.Effect<
  Organization,
  WorkosError<typeof createErrors>,
  WorkosClient
> => run(createOp, input);

// ===========================================================================
// organizations.delete — DELETE /organizations/{id}
// ===========================================================================

export const DeleteOrganizationInput = Schema.Struct({
  id: Schema.String,
});
export interface DeleteOrganizationInput extends Schema.Schema.Type<
  typeof DeleteOrganizationInput
> {}

// The spec documents only 200/202/403 for delete — a missing organization
// returns 403, not 404 — so `Forbidden` is the only declared error. (v1 also
// listed `NotFound`, which delete cannot actually produce.)
const deleteErrors = [Forbidden] as const;

const deleteOp: Operation<
  typeof DeleteOrganizationInput,
  typeof Schema.Void,
  typeof deleteErrors
> = {
  id: "organizations.delete",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/organizations/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: DeleteOrganizationInput,
  output: Schema.Void,
  errors: deleteErrors,
};

/** Permanently delete an organization. Cannot be undone. */
const deleteOrganization = (
  input: DeleteOrganizationInput,
): Effect.Effect<void, WorkosError<typeof deleteErrors>, WorkosClient> =>
  run(deleteOp, input);

// `delete` is a reserved word as a declaration name but a legal export name;
// the rename-export keeps the public surface on the API's own verb.
export { deleteOrganization as delete };

// ===========================================================================
// organizations.get — GET /organizations/{id}
// ===========================================================================

export const GetOrganizationInput = Schema.Struct({
  id: Schema.String,
});
export interface GetOrganizationInput extends Schema.Schema.Type<
  typeof GetOrganizationInput
> {}

const getErrors = [NotFound] as const;

const getOp: Operation<
  typeof GetOrganizationInput,
  typeof Organization,
  typeof getErrors
> = {
  id: "organizations.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organizations/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: GetOrganizationInput,
  output: Organization,
  errors: getErrors,
};

/** Fetch a single organization by id. */
export const get = (
  input: GetOrganizationInput,
): Effect.Effect<Organization, WorkosError<typeof getErrors>, WorkosClient> =>
  run(getOp, input);

// ===========================================================================
// organizations.getAuditLogConfiguration — GET /organizations/{id}/audit_log_configuration
// ===========================================================================

export const GetAuditLogConfigurationInput = Schema.Struct({
  id: Schema.String,
});
export interface GetAuditLogConfigurationInput extends Schema.Schema.Type<
  typeof GetAuditLogConfigurationInput
> {}

const getAuditLogConfigurationErrors = [NotFound] as const;

const getAuditLogConfigurationOp: Operation<
  typeof GetAuditLogConfigurationInput,
  typeof AuditLogConfiguration,
  typeof getAuditLogConfigurationErrors
> = {
  id: "organizations.getAuditLogConfiguration",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organizations/{id}/audit_log_configuration",
  pathParams: ["id"],
  queryParams: [],
  input: GetAuditLogConfigurationInput,
  output: AuditLogConfiguration,
  errors: getAuditLogConfigurationErrors,
};

/** Get the unified view of audit log trail and stream configuration for an organization. */
export const getAuditLogConfiguration = (
  input: GetAuditLogConfigurationInput,
): Effect.Effect<
  AuditLogConfiguration,
  WorkosError<typeof getAuditLogConfigurationErrors>,
  WorkosClient
> => run(getAuditLogConfigurationOp, input);

// ===========================================================================
// organizations.getByExternalId — GET /organizations/external_id/{external_id}
// ===========================================================================

export const GetOrganizationByExternalIdInput = Schema.Struct({
  external_id: Schema.String,
});
export interface GetOrganizationByExternalIdInput extends Schema.Schema.Type<
  typeof GetOrganizationByExternalIdInput
> {}

const getByExternalIdErrors = [NotFound] as const;

const getByExternalIdOp: Operation<
  typeof GetOrganizationByExternalIdInput,
  typeof Organization,
  typeof getByExternalIdErrors
> = {
  id: "organizations.getByExternalId",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organizations/external_id/{external_id}",
  pathParams: ["external_id"],
  queryParams: [],
  input: GetOrganizationByExternalIdInput,
  output: Organization,
  errors: getByExternalIdErrors,
};

/** Get the details of an existing organization by an [external identifier](/authkit/metadata/external-identifiers). */
export const getByExternalId = (
  input: GetOrganizationByExternalIdInput,
): Effect.Effect<
  Organization,
  WorkosError<typeof getByExternalIdErrors>,
  WorkosClient
> => run(getByExternalIdOp, input);

// ===========================================================================
// organizations.list — GET /organizations (cursor paginated)
// ===========================================================================

export const ListOrganizationsInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
  domains: Schema.optional(Schema.Array(Schema.String)),
  search: Schema.optional(Schema.String),
});
export interface ListOrganizationsInput extends Schema.Schema.Type<
  typeof ListOrganizationsInput
> {}

const listErrors = [UnprocessableEntity] as const;

const listOp: Operation<
  typeof ListOrganizationsInput,
  typeof OrganizationList,
  typeof listErrors
> = {
  id: "organizations.list",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organizations",
  pathParams: [],
  queryParams: ["before", "after", "limit", "order", "domains", "search"],
  input: ListOrganizationsInput,
  output: OrganizationList,
  errors: listErrors,
};

/** Fetch a single page of organizations. */
export const list = (
  input: ListOrganizationsInput = {},
): Effect.Effect<
  OrganizationList,
  WorkosError<typeof listErrors>,
  WorkosClient
> => run(listOp, input);

const listPagination: Pagination.CursorPagination<
  ListOrganizationsInput,
  OrganizationList,
  Organization
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of organizations, following the `after` cursor. */
export const listPages = (
  input: ListOrganizationsInput = {},
): Stream.Stream<
  OrganizationList,
  WorkosError<typeof listErrors>,
  WorkosClient
> => Pagination.pages(list, input, listPagination);

/** Stream every organization across every page. */
export const listItems = (
  input: ListOrganizationsInput = {},
): Stream.Stream<Organization, WorkosError<typeof listErrors>, WorkosClient> =>
  Pagination.items(list, input, listPagination);

// ===========================================================================
// organizations.listAuthorizedApplications — GET /organizations/{organization_id}/authorized_applications (cursor paginated)
// ===========================================================================

export const ListOrganizationAuthorizedApplicationsInput = Schema.Struct({
  organization_id: Schema.String,
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
});
export interface ListOrganizationAuthorizedApplicationsInput extends Schema
  .Schema.Type<typeof ListOrganizationAuthorizedApplicationsInput> {}

const listAuthorizedApplicationsErrors = [
  NotFound,
  UnprocessableEntity,
] as const;

const listAuthorizedApplicationsOp: Operation<
  typeof ListOrganizationAuthorizedApplicationsInput,
  typeof OrganizationAuthorizedConnectApplicationList,
  typeof listAuthorizedApplicationsErrors
> = {
  id: "organizations.listAuthorizedApplications",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organizations/{organization_id}/authorized_applications",
  pathParams: ["organization_id"],
  queryParams: ["before", "after", "limit", "order"],
  input: ListOrganizationAuthorizedApplicationsInput,
  output: OrganizationAuthorizedConnectApplicationList,
  errors: listAuthorizedApplicationsErrors,
};

/** Get a list of all Connect applications that users in the organization have authorized. */
export const listAuthorizedApplications = (
  input: ListOrganizationAuthorizedApplicationsInput,
): Effect.Effect<
  OrganizationAuthorizedConnectApplicationList,
  WorkosError<typeof listAuthorizedApplicationsErrors>,
  WorkosClient
> => run(listAuthorizedApplicationsOp, input);

const listAuthorizedApplicationsPagination: Pagination.CursorPagination<
  ListOrganizationAuthorizedApplicationsInput,
  OrganizationAuthorizedConnectApplicationList,
  OrganizationAuthorizedApplication
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of organizations, following the `after` cursor. */
export const listAuthorizedApplicationsPages = (
  input: ListOrganizationAuthorizedApplicationsInput,
): Stream.Stream<
  OrganizationAuthorizedConnectApplicationList,
  WorkosError<typeof listAuthorizedApplicationsErrors>,
  WorkosClient
> =>
  Pagination.pages(
    listAuthorizedApplications,
    input,
    listAuthorizedApplicationsPagination,
  );

/** Stream every organization authorized application across every page. */
export const listAuthorizedApplicationsItems = (
  input: ListOrganizationAuthorizedApplicationsInput,
): Stream.Stream<
  OrganizationAuthorizedApplication,
  WorkosError<typeof listAuthorizedApplicationsErrors>,
  WorkosClient
> =>
  Pagination.items(
    listAuthorizedApplications,
    input,
    listAuthorizedApplicationsPagination,
  );

// ===========================================================================
// organizations.update — PUT /organizations/{id}
// ===========================================================================

export const UpdateOrganizationInput = Schema.Struct({
  id: Schema.String,
  name: Schema.optional(Schema.String),
  allow_profiles_outside_organization: Schema.optional(Schema.Boolean),
  domains: Schema.optional(Schema.Array(Schema.String)),
  domain_data: Schema.optional(Schema.Array(OrganizationDomainDataDto)),
  stripe_customer_id: Schema.optional(Schema.String),
  metadata: Schema.optional(
    Schema.NullOr(Schema.Record(Schema.String, Schema.String)),
  ),
  external_id: Schema.optional(Schema.NullOr(Schema.String)),
});
export interface UpdateOrganizationInput extends Schema.Schema.Type<
  typeof UpdateOrganizationInput
> {}

const updateErrors = [
  Conflict,
  ExternalIdAlreadyUsed,
  Forbidden,
  InvalidMetadata,
  NotFound,
  StripeCustomerIdAlreadyUsed,
  UnprocessableEntity,
] as const;

const updateOp: Operation<
  typeof UpdateOrganizationInput,
  typeof Organization,
  typeof updateErrors
> = {
  id: "organizations.update",
  method: "PUT",
  retry: "throttling",
  pathTemplate: "/organizations/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: UpdateOrganizationInput,
  output: Organization,
  errors: updateErrors,
};

/** Updates an organization in the current environment. */
export const update = (
  input: UpdateOrganizationInput,
): Effect.Effect<
  Organization,
  WorkosError<typeof updateErrors>,
  WorkosClient
> => run(updateOp, input);
