/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  Conflict,
  NotFound,
  type Operation,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import {
  OrganizationDomainCreateResponse,
  OrganizationDomainStandAlone,
} from "../schemas.ts";

// ===========================================================================
// organizationDomains.create — POST /organization_domains
// ===========================================================================

export const CreateOrganizationDomainInput = Schema.Struct({
  domain: Schema.String,
  organization_id: Schema.String,
});
export interface CreateOrganizationDomainInput extends Schema.Schema.Type<
  typeof CreateOrganizationDomainInput
> {}

const createErrors = [Conflict] as const;

const createOp: Operation<
  typeof CreateOrganizationDomainInput,
  typeof OrganizationDomainCreateResponse,
  typeof createErrors
> = {
  id: "organizationDomains.create",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/organization_domains",
  pathParams: [],
  queryParams: [],
  input: CreateOrganizationDomainInput,
  output: OrganizationDomainCreateResponse,
  errors: createErrors,
};

/** Creates a new Organization Domain. */
export const create = (
  input: CreateOrganizationDomainInput,
): Effect.Effect<
  OrganizationDomainCreateResponse,
  WorkosError<typeof createErrors>,
  WorkosClient
> => run(createOp, input);

// ===========================================================================
// organizationDomains.delete — DELETE /organization_domains/{id}
// ===========================================================================

export const DeleteOrganizationDomainInput = Schema.Struct({
  id: Schema.String,
});
export interface DeleteOrganizationDomainInput extends Schema.Schema.Type<
  typeof DeleteOrganizationDomainInput
> {}

const deleteErrors = [NotFound] as const;

const deleteOp: Operation<
  typeof DeleteOrganizationDomainInput,
  typeof Schema.Void,
  typeof deleteErrors
> = {
  id: "organizationDomains.delete",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/organization_domains/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: DeleteOrganizationDomainInput,
  output: Schema.Void,
  errors: deleteErrors,
};

/** Permanently deletes an organization domain. It cannot be undone. */
const deleteOrganizationDomain = (
  input: DeleteOrganizationDomainInput,
): Effect.Effect<void, WorkosError<typeof deleteErrors>, WorkosClient> =>
  run(deleteOp, input);

// `delete` is a reserved word as a declaration name but a legal export name;
// the rename-export keeps the public surface on the API's own verb.
export { deleteOrganizationDomain as delete };

// ===========================================================================
// organizationDomains.get — GET /organization_domains/{id}
// ===========================================================================

export const GetOrganizationDomainInput = Schema.Struct({
  id: Schema.String,
});
export interface GetOrganizationDomainInput extends Schema.Schema.Type<
  typeof GetOrganizationDomainInput
> {}

const getErrors = [NotFound] as const;

const getOp: Operation<
  typeof GetOrganizationDomainInput,
  typeof OrganizationDomainStandAlone,
  typeof getErrors
> = {
  id: "organizationDomains.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organization_domains/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: GetOrganizationDomainInput,
  output: OrganizationDomainStandAlone,
  errors: getErrors,
};

/** Get the details of an existing organization domain. */
export const get = (
  input: GetOrganizationDomainInput,
): Effect.Effect<
  OrganizationDomainStandAlone,
  WorkosError<typeof getErrors>,
  WorkosClient
> => run(getOp, input);

// ===========================================================================
// organizationDomains.verify — POST /organization_domains/{id}/verify
// ===========================================================================

export const VerifyOrganizationDomainInput = Schema.Struct({
  id: Schema.String,
});
export interface VerifyOrganizationDomainInput extends Schema.Schema.Type<
  typeof VerifyOrganizationDomainInput
> {}

const verifyErrors = [BadRequest] as const;

const verifyOp: Operation<
  typeof VerifyOrganizationDomainInput,
  typeof OrganizationDomainStandAlone,
  typeof verifyErrors
> = {
  id: "organizationDomains.verify",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/organization_domains/{id}/verify",
  pathParams: ["id"],
  queryParams: [],
  input: VerifyOrganizationDomainInput,
  output: OrganizationDomainStandAlone,
  errors: verifyErrors,
};

/** Initiates verification process for an Organization Domain. */
export const verify = (
  input: VerifyOrganizationDomainInput,
): Effect.Effect<
  OrganizationDomainStandAlone,
  WorkosError<typeof verifyErrors>,
  WorkosClient
> => run(verifyOp, input);
