/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  Conflict,
  Forbidden,
  NotFound,
  type Operation,
  Pagination,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import { Organization, OrganizationList } from "../schemas.ts";

// ===========================================================================
// organizations.create — POST /organizations
// ===========================================================================

export const CreateOrganizationInput = Schema.Struct({
  name: Schema.String,
  domains: Schema.optional(Schema.Array(Schema.String)),
  domain_data: Schema.optional(
    Schema.Array(
      Schema.Struct({
        domain: Schema.String,
        state: Schema.Literals(["pending", "verified"]),
      }),
    ),
  ),
  metadata: Schema.optional(
    Schema.NullOr(Schema.Record(Schema.String, Schema.String)),
  ),
  external_id: Schema.optional(Schema.NullOr(Schema.String)),
  allow_profiles_outside_organization: Schema.optional(Schema.Boolean),
});
export interface CreateOrganizationInput extends Schema.Schema.Type<
  typeof CreateOrganizationInput
> {}

const createErrors = [BadRequest, Conflict, UnprocessableEntity] as const;

const createOp: Operation<
  typeof CreateOrganizationInput,
  typeof Organization,
  typeof createErrors
> = {
  id: "organizations.create",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/organizations",
  pathParams: [],
  queryParams: [],
  input: CreateOrganizationInput,
  output: Organization,
  errors: createErrors,
};

/** Create an organization in the current environment. */
export const create = (
  input: CreateOrganizationInput,
): Effect.Effect<
  Organization,
  WorkosError<typeof createErrors>,
  WorkosClient
> => run(createOp, input);

// ===========================================================================
// organizations.get — GET /organizations/{id}
// ===========================================================================

export const GetOrganizationInput = Schema.Struct({
  id: Schema.String,
});
export interface GetOrganizationInput extends Schema.Schema.Type<
  typeof GetOrganizationInput
> {}

const getErrors = [NotFound] as const;

const getOp: Operation<
  typeof GetOrganizationInput,
  typeof Organization,
  typeof getErrors
> = {
  id: "organizations.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organizations/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: GetOrganizationInput,
  output: Organization,
  errors: getErrors,
};

/** Fetch a single organization by id. */
export const get = (
  input: GetOrganizationInput,
): Effect.Effect<Organization, WorkosError<typeof getErrors>, WorkosClient> =>
  run(getOp, input);

// ===========================================================================
// organizations.delete — DELETE /organizations/{id}
// ===========================================================================

export const DeleteOrganizationInput = Schema.Struct({
  id: Schema.String,
});
export interface DeleteOrganizationInput extends Schema.Schema.Type<
  typeof DeleteOrganizationInput
> {}

// The spec documents only 200/202/403 for delete — a missing organization
// returns 403, not 404 — so `Forbidden` is the only declared error. (v1 also
// listed `NotFound`, which delete cannot actually produce.)
const deleteErrors = [Forbidden] as const;

const deleteOp: Operation<
  typeof DeleteOrganizationInput,
  typeof Schema.Void,
  typeof deleteErrors
> = {
  id: "organizations.delete",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/organizations/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: DeleteOrganizationInput,
  output: Schema.Void,
  errors: deleteErrors,
};

/** Permanently delete an organization. Cannot be undone. */
const deleteOrganization = (
  input: DeleteOrganizationInput,
): Effect.Effect<void, WorkosError<typeof deleteErrors>, WorkosClient> =>
  run(deleteOp, input);

// `delete` is a reserved word as a declaration name but a legal export name;
// the rename-export keeps the public surface on the API's own verb.
export { deleteOrganization as delete };

// ===========================================================================
// organizations.list — GET /organizations (cursor paginated)
// ===========================================================================

export const ListOrganizationsInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["asc", "desc", "normal"])),
  domains: Schema.optional(Schema.Array(Schema.String)),
  search: Schema.optional(Schema.String),
});
export interface ListOrganizationsInput extends Schema.Schema.Type<
  typeof ListOrganizationsInput
> {}

const listErrors = [UnprocessableEntity] as const;

const listOp: Operation<
  typeof ListOrganizationsInput,
  typeof OrganizationList,
  typeof listErrors
> = {
  id: "organizations.list",
  method: "GET",
  retry: "transient",
  pathTemplate: "/organizations",
  pathParams: [],
  queryParams: ["before", "after", "limit", "order", "domains", "search"],
  input: ListOrganizationsInput,
  output: OrganizationList,
  errors: listErrors,
};

/** Fetch a single page of organizations. */
export const list = (
  input: ListOrganizationsInput = {},
): Effect.Effect<
  OrganizationList,
  WorkosError<typeof listErrors>,
  WorkosClient
> => run(listOp, input);

const listPagination: Pagination.CursorPagination<
  ListOrganizationsInput,
  OrganizationList,
  Organization
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of organizations, following the `after` cursor. */
export const listPages = (
  input: ListOrganizationsInput = {},
): Stream.Stream<
  OrganizationList,
  WorkosError<typeof listErrors>,
  WorkosClient
> => Pagination.pages(list, input, listPagination);

/** Stream every organization across every page. */
export const listItems = (
  input: ListOrganizationsInput = {},
): Stream.Stream<Organization, WorkosError<typeof listErrors>, WorkosClient> =>
  Pagination.items(list, input, listPagination);
