/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  Conflict,
  Forbidden,
  NotFound,
  type Operation,
  Pagination,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import {
  AuthorizationPermission,
  AuthorizationPermissionCreateResponse,
  AuthorizationPermissionList,
} from "../schemas.ts";

// ===========================================================================
// permissions.create — POST /authorization/permissions
// ===========================================================================

export const CreatePermissionInput = Schema.Struct({
  slug: Schema.String,
  name: Schema.String,
  description: Schema.optional(Schema.NullOr(Schema.String)),
  resource_type_slug: Schema.optional(Schema.String),
});
export interface CreatePermissionInput extends Schema.Schema.Type<
  typeof CreatePermissionInput
> {}

const createErrors = [
  BadRequest,
  Conflict,
  NotFound,
  UnprocessableEntity,
] as const;

const createOp: Operation<
  typeof CreatePermissionInput,
  typeof AuthorizationPermissionCreateResponse,
  typeof createErrors
> = {
  id: "permissions.create",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/authorization/permissions",
  pathParams: [],
  queryParams: [],
  input: CreatePermissionInput,
  output: AuthorizationPermissionCreateResponse,
  errors: createErrors,
};

/** Create a new permission in your WorkOS environment. The permission can then be assigned to environment roles and custom roles. */
export const create = (
  input: CreatePermissionInput,
): Effect.Effect<
  AuthorizationPermissionCreateResponse,
  WorkosError<typeof createErrors>,
  WorkosClient
> => run(createOp, input);

// ===========================================================================
// permissions.delete — DELETE /authorization/permissions/{slug}
// ===========================================================================

export const DeletePermissionInput = Schema.Struct({
  slug: Schema.String,
});
export interface DeletePermissionInput extends Schema.Schema.Type<
  typeof DeletePermissionInput
> {}

const deleteErrors = [Forbidden, NotFound] as const;

const deleteOp: Operation<
  typeof DeletePermissionInput,
  typeof Schema.Void,
  typeof deleteErrors
> = {
  id: "permissions.delete",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/authorization/permissions/{slug}",
  pathParams: ["slug"],
  queryParams: [],
  input: DeletePermissionInput,
  output: Schema.Void,
  errors: deleteErrors,
};

/** Delete an existing permission. System permissions cannot be deleted. */
const deletePermission = (
  input: DeletePermissionInput,
): Effect.Effect<void, WorkosError<typeof deleteErrors>, WorkosClient> =>
  run(deleteOp, input);

// `delete` is a reserved word as a declaration name but a legal export name;
// the rename-export keeps the public surface on the API's own verb.
export { deletePermission as delete };

// ===========================================================================
// permissions.get — GET /authorization/permissions/{slug}
// ===========================================================================

export const GetPermissionInput = Schema.Struct({
  slug: Schema.String,
});
export interface GetPermissionInput extends Schema.Schema.Type<
  typeof GetPermissionInput
> {}

const getErrors = [NotFound] as const;

const getOp: Operation<
  typeof GetPermissionInput,
  typeof AuthorizationPermission,
  typeof getErrors
> = {
  id: "permissions.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/authorization/permissions/{slug}",
  pathParams: ["slug"],
  queryParams: [],
  input: GetPermissionInput,
  output: AuthorizationPermission,
  errors: getErrors,
};

/** Retrieve a permission by its unique slug. */
export const get = (
  input: GetPermissionInput,
): Effect.Effect<
  AuthorizationPermission,
  WorkosError<typeof getErrors>,
  WorkosClient
> => run(getOp, input);

// ===========================================================================
// permissions.list — GET /authorization/permissions (cursor paginated)
// ===========================================================================

export const ListPermissionsInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
});
export interface ListPermissionsInput extends Schema.Schema.Type<
  typeof ListPermissionsInput
> {}

const listErrors = [NotFound] as const;

const listOp: Operation<
  typeof ListPermissionsInput,
  typeof AuthorizationPermissionList,
  typeof listErrors
> = {
  id: "permissions.list",
  method: "GET",
  retry: "transient",
  pathTemplate: "/authorization/permissions",
  pathParams: [],
  queryParams: ["before", "after", "limit", "order"],
  input: ListPermissionsInput,
  output: AuthorizationPermissionList,
  errors: listErrors,
};

/** Get a list of all permissions in your WorkOS environment. */
export const list = (
  input: ListPermissionsInput = {},
): Effect.Effect<
  AuthorizationPermissionList,
  WorkosError<typeof listErrors>,
  WorkosClient
> => run(listOp, input);

const listPagination: Pagination.CursorPagination<
  ListPermissionsInput,
  AuthorizationPermissionList,
  AuthorizationPermission
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of permissions, following the `after` cursor. */
export const listPages = (
  input: ListPermissionsInput = {},
): Stream.Stream<
  AuthorizationPermissionList,
  WorkosError<typeof listErrors>,
  WorkosClient
> => Pagination.pages(list, input, listPagination);

/** Stream every authorization permission across every page. */
export const listItems = (
  input: ListPermissionsInput = {},
): Stream.Stream<
  AuthorizationPermission,
  WorkosError<typeof listErrors>,
  WorkosClient
> => Pagination.items(list, input, listPagination);

// ===========================================================================
// permissions.update — PATCH /authorization/permissions/{slug}
// ===========================================================================

export const UpdatePermissionInput = Schema.Struct({
  slug: Schema.String,
  name: Schema.optional(Schema.String),
  description: Schema.optional(Schema.NullOr(Schema.String)),
});
export interface UpdatePermissionInput extends Schema.Schema.Type<
  typeof UpdatePermissionInput
> {}

const updateErrors = [Forbidden, NotFound, UnprocessableEntity] as const;

const updateOp: Operation<
  typeof UpdatePermissionInput,
  typeof AuthorizationPermission,
  typeof updateErrors
> = {
  id: "permissions.update",
  method: "PATCH",
  retry: "throttling",
  pathTemplate: "/authorization/permissions/{slug}",
  pathParams: ["slug"],
  queryParams: [],
  input: UpdatePermissionInput,
  output: AuthorizationPermission,
  errors: updateErrors,
};

/** Update an existing permission. Only the fields provided in the request body will be updated. */
export const update = (
  input: UpdatePermissionInput,
): Effect.Effect<
  AuthorizationPermission,
  WorkosError<typeof updateErrors>,
  WorkosClient
> => run(updateOp, input);
