/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  NotFound,
  type Operation,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import {
  RadarListEntryAlreadyPresentResponse,
  RadarStandaloneResponse,
} from "../schemas.ts";

// ===========================================================================
// radar.addListEntry — POST /radar/lists/{type}/{action}
// ===========================================================================

export const AddListEntryInput = Schema.Struct({
  type: Schema.Literals([
    "ip_address",
    "domain",
    "email",
    "device",
    "user_agent",
    "device_fingerprint",
    "country",
  ]),
  action: Schema.Literals(["block", "allow"]),
  entry: Schema.String,
});
export interface AddListEntryInput extends Schema.Schema.Type<
  typeof AddListEntryInput
> {}

const addListEntryErrors = [BadRequest] as const;

const addListEntryOp: Operation<
  typeof AddListEntryInput,
  typeof RadarListEntryAlreadyPresentResponse,
  typeof addListEntryErrors
> = {
  id: "radar.addListEntry",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/radar/lists/{type}/{action}",
  pathParams: ["type", "action"],
  queryParams: [],
  input: AddListEntryInput,
  output: RadarListEntryAlreadyPresentResponse,
  errors: addListEntryErrors,
};

/** Add an entry to a Radar list. */
export const addListEntry = (
  input: AddListEntryInput,
): Effect.Effect<
  RadarListEntryAlreadyPresentResponse,
  WorkosError<typeof addListEntryErrors>,
  WorkosClient
> => run(addListEntryOp, input);

// ===========================================================================
// radar.createAttempt — POST /radar/attempts
// ===========================================================================

export const CreateAttemptInput = Schema.Struct({
  ip_address: Schema.String,
  user_agent: Schema.String,
  email: Schema.String,
  auth_method: Schema.Literals([
    "Password",
    "Passkey",
    "Authenticator",
    "SMS_OTP",
    "Email_OTP",
    "Social",
    "SSO",
    "Other",
  ]),
  action: Schema.Literals(["sign-up", "sign-in"]),
  signals_id: Schema.optional(Schema.String),
});
export interface CreateAttemptInput extends Schema.Schema.Type<
  typeof CreateAttemptInput
> {}

const createAttemptErrors = [BadRequest] as const;

const createAttemptOp: Operation<
  typeof CreateAttemptInput,
  typeof RadarStandaloneResponse,
  typeof createAttemptErrors
> = {
  id: "radar.createAttempt",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/radar/attempts",
  pathParams: [],
  queryParams: [],
  input: CreateAttemptInput,
  output: RadarStandaloneResponse,
  errors: createAttemptErrors,
};

/** Assess a request for risk using the Radar engine and receive a verdict. */
export const createAttempt = (
  input: CreateAttemptInput,
): Effect.Effect<
  RadarStandaloneResponse,
  WorkosError<typeof createAttemptErrors>,
  WorkosClient
> => run(createAttemptOp, input);

// ===========================================================================
// radar.removeListEntry — DELETE /radar/lists/{type}/{action}
// ===========================================================================

export const RemoveListEntryInput = Schema.Struct({
  type: Schema.Literals([
    "ip_address",
    "domain",
    "email",
    "device",
    "user_agent",
    "device_fingerprint",
    "country",
  ]),
  action: Schema.Literals(["block", "allow"]),
  entry: Schema.String,
});
export interface RemoveListEntryInput extends Schema.Schema.Type<
  typeof RemoveListEntryInput
> {}

const removeListEntryErrors = [BadRequest, NotFound] as const;

const removeListEntryOp: Operation<
  typeof RemoveListEntryInput,
  typeof Schema.Void,
  typeof removeListEntryErrors
> = {
  id: "radar.removeListEntry",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/radar/lists/{type}/{action}",
  pathParams: ["type", "action"],
  queryParams: [],
  input: RemoveListEntryInput,
  output: Schema.Void,
  errors: removeListEntryErrors,
};

/** Remove an entry from a Radar list. */
export const removeListEntry = (
  input: RemoveListEntryInput,
): Effect.Effect<
  void,
  WorkosError<typeof removeListEntryErrors>,
  WorkosClient
> => run(removeListEntryOp, input);

// ===========================================================================
// radar.updateAttempt — PUT /radar/attempts/{id}
// ===========================================================================

export const UpdateAttemptInput = Schema.Struct({
  id: Schema.String,
  challenge_status: Schema.optional(Schema.Literal("success")),
  attempt_status: Schema.optional(Schema.Literal("success")),
});
export interface UpdateAttemptInput extends Schema.Schema.Type<
  typeof UpdateAttemptInput
> {}

const updateAttemptErrors = [BadRequest, NotFound] as const;

const updateAttemptOp: Operation<
  typeof UpdateAttemptInput,
  typeof Schema.Void,
  typeof updateAttemptErrors
> = {
  id: "radar.updateAttempt",
  method: "PUT",
  retry: "throttling",
  pathTemplate: "/radar/attempts/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: UpdateAttemptInput,
  output: Schema.Void,
  errors: updateAttemptErrors,
};

/** You may optionally inform Radar that an authentication attempt or challenge was successful using this endpoint. Some Radar controls depend on tracking recent successful attempts, such as impossible travel. */
export const updateAttempt = (
  input: UpdateAttemptInput,
): Effect.Effect<void, WorkosError<typeof updateAttemptErrors>, WorkosClient> =>
  run(updateAttemptOp, input);
