/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  NotFound,
  type Operation,
  Secret,
  Unauthorized,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import {
  ConnectionInvalid,
  InvalidClient,
  InvalidGrant,
  UnauthorizedClient,
  UnsupportedGrantType,
} from "../errors.ts";
import {
  Profile,
  SsoAuthorizeUrlResponse,
  SsoLogoutAuthorizeResponse,
  SsoTokenResponse,
} from "../schemas.ts";

// ===========================================================================
// sso.getAuthorizationUrl — GET /sso/authorize
// ===========================================================================

export const GetSsoAuthorizationUrlInput = Schema.Struct({
  provider_scopes: Schema.optional(Schema.Array(Schema.String)),
  provider_query_params: Schema.optional(
    Schema.Record(Schema.String, Schema.String),
  ),
  client_id: Schema.String,
  domain: Schema.optional(Schema.String),
  provider: Schema.optional(
    Schema.Literals([
      "AppleOAuth",
      "BitbucketOAuth",
      "GitHubOAuth",
      "GitLabOAuth",
      "GoogleOAuth",
      "IntuitOAuth",
      "LinkedInOAuth",
      "MicrosoftOAuth",
      "SalesforceOAuth",
      "SlackOAuth",
      "VercelMarketplaceOAuth",
      "VercelOAuth",
      "XeroOAuth",
    ]),
  ),
  redirect_uri: Schema.String,
  response_type: Schema.Literal("code"),
  state: Schema.optional(Schema.String),
  connection: Schema.optional(Schema.String),
  organization: Schema.optional(Schema.String),
  domain_hint: Schema.optional(Schema.String),
  login_hint: Schema.optional(Schema.String),
  nonce: Schema.optional(Schema.String),
  prompt: Schema.optional(Schema.Literal("login")),
});
export interface GetSsoAuthorizationUrlInput extends Schema.Schema.Type<
  typeof GetSsoAuthorizationUrlInput
> {}

const getAuthorizationUrlErrors = [] as const;

const getAuthorizationUrlOp: Operation<
  typeof GetSsoAuthorizationUrlInput,
  typeof SsoAuthorizeUrlResponse,
  typeof getAuthorizationUrlErrors
> = {
  id: "sso.getAuthorizationUrl",
  method: "GET",
  retry: "transient",
  pathTemplate: "/sso/authorize",
  pathParams: [],
  queryParams: [
    "provider_scopes",
    "provider_query_params",
    "client_id",
    "domain",
    "provider",
    "redirect_uri",
    "response_type",
    "state",
    "connection",
    "organization",
    "domain_hint",
    "login_hint",
    "nonce",
    "prompt",
  ],
  input: GetSsoAuthorizationUrlInput,
  output: SsoAuthorizeUrlResponse,
  errors: getAuthorizationUrlErrors,
};

/** Initiates the single sign-on flow. */
export const getAuthorizationUrl = (
  input: GetSsoAuthorizationUrlInput,
): Effect.Effect<
  SsoAuthorizeUrlResponse,
  WorkosError<typeof getAuthorizationUrlErrors>,
  WorkosClient
> => run(getAuthorizationUrlOp, input);

// ===========================================================================
// sso.getLogoutUrl — GET /sso/logout
// ===========================================================================

export const GetSsoLogoutUrlInput = Schema.Struct({
  token: Schema.String,
});
export interface GetSsoLogoutUrlInput extends Schema.Schema.Type<
  typeof GetSsoLogoutUrlInput
> {}

const getLogoutUrlErrors = [NotFound] as const;

const getLogoutUrlOp: Operation<
  typeof GetSsoLogoutUrlInput,
  typeof Schema.Void,
  typeof getLogoutUrlErrors
> = {
  id: "sso.getLogoutUrl",
  method: "GET",
  retry: "transient",
  pathTemplate: "/sso/logout",
  pathParams: [],
  queryParams: ["token"],
  input: GetSsoLogoutUrlInput,
  output: Schema.Void,
  errors: getLogoutUrlErrors,
};

/**
 * Logout allows to sign out a user from your application by triggering the identity provider sign out flow. This `GET` endpoint should be a redirection, since the identity provider user will be identified in the browser session.
 *
 * Before redirecting to this endpoint, you need to generate a short-lived logout token using the [Logout Authorize](/reference/sso/logout/authorize) endpoint.
 */
export const getLogoutUrl = (
  input: GetSsoLogoutUrlInput,
): Effect.Effect<void, WorkosError<typeof getLogoutUrlErrors>, WorkosClient> =>
  run(getLogoutUrlOp, input);

// ===========================================================================
// sso.getProfile — GET /sso/profile
// ===========================================================================

export const GetProfileInput = Schema.Struct({});
export interface GetProfileInput extends Schema.Schema.Type<
  typeof GetProfileInput
> {}

const getProfileErrors = [NotFound, Unauthorized] as const;

const getProfileOp: Operation<
  typeof GetProfileInput,
  typeof Profile,
  typeof getProfileErrors
> = {
  id: "sso.getProfile",
  method: "GET",
  retry: "transient",
  pathTemplate: "/sso/profile",
  pathParams: [],
  queryParams: [],
  input: GetProfileInput,
  output: Profile,
  errors: getProfileErrors,
};

/** Exchange an access token for a user's [Profile](/reference/sso/profile). Because this profile is returned in the [Get a Profile and Token endpoint](/reference/sso/profile/get-profile-and-token) your application usually does not need to call this endpoint. It is available for any authentication flows that require an additional endpoint to retrieve a user's profile. */
export const getProfile = (
  input: GetProfileInput = {},
): Effect.Effect<Profile, WorkosError<typeof getProfileErrors>, WorkosClient> =>
  run(getProfileOp, input);

// ===========================================================================
// sso.getProfileAndToken — POST /sso/token
// ===========================================================================

export const GetProfileAndTokenInput = Schema.Struct({
  client_id: Schema.String,
  client_secret: Secret,
  code: Schema.String,
});
export interface GetProfileAndTokenInput extends Schema.Schema.Type<
  typeof GetProfileAndTokenInput
> {}

const getProfileAndTokenErrors = [
  InvalidClient,
  InvalidGrant,
  NotFound,
  UnauthorizedClient,
  UnprocessableEntity,
  UnsupportedGrantType,
] as const;

const getProfileAndTokenOp: Operation<
  typeof GetProfileAndTokenInput,
  typeof SsoTokenResponse,
  typeof getProfileAndTokenErrors
> = {
  id: "sso.getProfileAndToken",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/sso/token",
  pathParams: [],
  queryParams: [],
  input: GetProfileAndTokenInput,
  output: SsoTokenResponse,
  errors: getProfileAndTokenErrors,
  constantBody: { grant_type: "authorization_code" },
};

/** Get an access token along with the user [Profile](/reference/sso/profile) using the code passed to your [Redirect URI](/reference/sso/get-authorization-url/redirect-uri). */
export const getProfileAndToken = (
  input: GetProfileAndTokenInput,
): Effect.Effect<
  SsoTokenResponse,
  WorkosError<typeof getProfileAndTokenErrors>,
  WorkosClient
> => run(getProfileAndTokenOp, input);

// ===========================================================================
// sso.logoutAuthorize — POST /sso/logout/authorize
// ===========================================================================

export const SsoLogoutAuthorizeInput = Schema.Struct({
  profile_id: Schema.String,
});
export interface SsoLogoutAuthorizeInput extends Schema.Schema.Type<
  typeof SsoLogoutAuthorizeInput
> {}

const logoutAuthorizeErrors = [
  ConnectionInvalid,
  NotFound,
  UnauthorizedClient,
] as const;

const logoutAuthorizeOp: Operation<
  typeof SsoLogoutAuthorizeInput,
  typeof SsoLogoutAuthorizeResponse,
  typeof logoutAuthorizeErrors
> = {
  id: "sso.logoutAuthorize",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/sso/logout/authorize",
  pathParams: [],
  queryParams: [],
  input: SsoLogoutAuthorizeInput,
  output: SsoLogoutAuthorizeResponse,
  errors: logoutAuthorizeErrors,
};

/** You should call this endpoint from your server to generate a logout token which is required for the [Logout Redirect](/reference/sso/logout) endpoint. */
export const logoutAuthorize = (
  input: SsoLogoutAuthorizeInput,
): Effect.Effect<
  SsoLogoutAuthorizeResponse,
  WorkosError<typeof logoutAuthorizeErrors>,
  WorkosClient
> => run(logoutAuthorizeOp, input);
