/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  Conflict,
  InternalServerError,
  NotFound,
  type Operation,
  Pagination,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import {
  CreateDataKeyResponse,
  DecryptResponse,
  DeleteObjectResponse,
  ObjectListResponse,
  ObjectMetadata,
  ObjectSummary,
  ObjectWithoutValue,
  VaultObject,
  VersionListResponse,
} from "../schemas.ts";

// ===========================================================================
// vault.createDataKey — POST /vault/v1/keys/data-key
// ===========================================================================

export const CreateDataKeyInput = Schema.Struct({
  context: Schema.Record(Schema.String, Schema.String),
});
export interface CreateDataKeyInput extends Schema.Schema.Type<
  typeof CreateDataKeyInput
> {}

const createDataKeyErrors = [BadRequest, UnprocessableEntity] as const;

const createDataKeyOp: Operation<
  typeof CreateDataKeyInput,
  typeof CreateDataKeyResponse,
  typeof createDataKeyErrors
> = {
  id: "vault.createDataKey",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/vault/v1/keys/data-key",
  pathParams: [],
  queryParams: [],
  input: CreateDataKeyInput,
  output: CreateDataKeyResponse,
  errors: createDataKeyErrors,
};

/** Generate an isolated encryption key for local encryption operations. */
export const createDataKey = (
  input: CreateDataKeyInput,
): Effect.Effect<
  CreateDataKeyResponse,
  WorkosError<typeof createDataKeyErrors>,
  WorkosClient
> => run(createDataKeyOp, input);

// ===========================================================================
// vault.createObject — POST /vault/v1/kv
// ===========================================================================

export const CreateObjectInput = Schema.Struct({
  key_context: Schema.Record(Schema.String, Schema.String),
  name: Schema.String,
  value: Schema.String,
});
export interface CreateObjectInput extends Schema.Schema.Type<
  typeof CreateObjectInput
> {}

const createObjectErrors = [BadRequest, Conflict, UnprocessableEntity] as const;

const createObjectOp: Operation<
  typeof CreateObjectInput,
  typeof ObjectMetadata,
  typeof createObjectErrors
> = {
  id: "vault.createObject",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/vault/v1/kv",
  pathParams: [],
  queryParams: [],
  input: CreateObjectInput,
  output: ObjectMetadata,
  errors: createObjectErrors,
};

/** Encrypt and store a new key-value object. */
export const createObject = (
  input: CreateObjectInput,
): Effect.Effect<
  ObjectMetadata,
  WorkosError<typeof createObjectErrors>,
  WorkosClient
> => run(createObjectOp, input);

// ===========================================================================
// vault.decryptDataKey — POST /vault/v1/keys/decrypt
// ===========================================================================

export const DecryptDataKeyInput = Schema.Struct({
  keys: Schema.String,
});
export interface DecryptDataKeyInput extends Schema.Schema.Type<
  typeof DecryptDataKeyInput
> {}

const decryptDataKeyErrors = [BadRequest] as const;

const decryptDataKeyOp: Operation<
  typeof DecryptDataKeyInput,
  typeof DecryptResponse,
  typeof decryptDataKeyErrors
> = {
  id: "vault.decryptDataKey",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/vault/v1/keys/decrypt",
  pathParams: [],
  queryParams: [],
  input: DecryptDataKeyInput,
  output: DecryptResponse,
  errors: decryptDataKeyErrors,
};

/** Decrypt a previously encrypted data key from WorkOS Vault. */
export const decryptDataKey = (
  input: DecryptDataKeyInput,
): Effect.Effect<
  DecryptResponse,
  WorkosError<typeof decryptDataKeyErrors>,
  WorkosClient
> => run(decryptDataKeyOp, input);

// ===========================================================================
// vault.deleteObject — DELETE /vault/v1/kv/{id}
// ===========================================================================

export const DeleteObjectInput = Schema.Struct({
  id: Schema.String,
  version_check: Schema.optional(Schema.String),
});
export interface DeleteObjectInput extends Schema.Schema.Type<
  typeof DeleteObjectInput
> {}

const deleteObjectErrors = [Conflict, InternalServerError, NotFound] as const;

const deleteObjectOp: Operation<
  typeof DeleteObjectInput,
  typeof DeleteObjectResponse,
  typeof deleteObjectErrors
> = {
  id: "vault.deleteObject",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/vault/v1/kv/{id}",
  pathParams: ["id"],
  queryParams: ["version_check"],
  input: DeleteObjectInput,
  output: DeleteObjectResponse,
  errors: deleteObjectErrors,
};

/** Delete an encrypted object. */
export const deleteObject = (
  input: DeleteObjectInput,
): Effect.Effect<
  DeleteObjectResponse,
  WorkosError<typeof deleteObjectErrors>,
  WorkosClient
> => run(deleteObjectOp, input);

// ===========================================================================
// vault.describeObject — GET /vault/v1/kv/{id}/metadata
// ===========================================================================

export const DescribeObjectInput = Schema.Struct({
  id: Schema.String,
});
export interface DescribeObjectInput extends Schema.Schema.Type<
  typeof DescribeObjectInput
> {}

const describeObjectErrors = [BadRequest, NotFound] as const;

const describeObjectOp: Operation<
  typeof DescribeObjectInput,
  typeof ObjectWithoutValue,
  typeof describeObjectErrors
> = {
  id: "vault.describeObject",
  method: "GET",
  retry: "transient",
  pathTemplate: "/vault/v1/kv/{id}/metadata",
  pathParams: ["id"],
  queryParams: [],
  input: DescribeObjectInput,
  output: ObjectWithoutValue,
  errors: describeObjectErrors,
};

/** Fetch metadata for an object without decrypting it. */
export const describeObject = (
  input: DescribeObjectInput,
): Effect.Effect<
  ObjectWithoutValue,
  WorkosError<typeof describeObjectErrors>,
  WorkosClient
> => run(describeObjectOp, input);

// ===========================================================================
// vault.getObject — GET /vault/v1/kv/{id}
// ===========================================================================

export const GetObjectInput = Schema.Struct({
  id: Schema.String,
});
export interface GetObjectInput extends Schema.Schema.Type<
  typeof GetObjectInput
> {}

const getObjectErrors = [BadRequest, NotFound] as const;

const getObjectOp: Operation<
  typeof GetObjectInput,
  typeof VaultObject,
  typeof getObjectErrors
> = {
  id: "vault.getObject",
  method: "GET",
  retry: "transient",
  pathTemplate: "/vault/v1/kv/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: GetObjectInput,
  output: VaultObject,
  errors: getObjectErrors,
};

/** Fetch and decrypt an object by its unique identifier. */
export const getObject = (
  input: GetObjectInput,
): Effect.Effect<
  VaultObject,
  WorkosError<typeof getObjectErrors>,
  WorkosClient
> => run(getObjectOp, input);

// ===========================================================================
// vault.getObjectByName — GET /vault/v1/kv/name/{name}
// ===========================================================================

export const GetObjectByNameInput = Schema.Struct({
  name: Schema.String,
});
export interface GetObjectByNameInput extends Schema.Schema.Type<
  typeof GetObjectByNameInput
> {}

const getObjectByNameErrors = [BadRequest, NotFound] as const;

const getObjectByNameOp: Operation<
  typeof GetObjectByNameInput,
  typeof VaultObject,
  typeof getObjectByNameErrors
> = {
  id: "vault.getObjectByName",
  method: "GET",
  retry: "transient",
  pathTemplate: "/vault/v1/kv/name/{name}",
  pathParams: ["name"],
  queryParams: [],
  input: GetObjectByNameInput,
  output: VaultObject,
  errors: getObjectByNameErrors,
};

/** Fetch and decrypt an object by its unique name. */
export const getObjectByName = (
  input: GetObjectByNameInput,
): Effect.Effect<
  VaultObject,
  WorkosError<typeof getObjectByNameErrors>,
  WorkosClient
> => run(getObjectByNameOp, input);

// ===========================================================================
// vault.listObjectVersions — GET /vault/v1/kv/{id}/versions
// ===========================================================================

export const ListObjectVersionsInput = Schema.Struct({
  id: Schema.String,
});
export interface ListObjectVersionsInput extends Schema.Schema.Type<
  typeof ListObjectVersionsInput
> {}

const listObjectVersionsErrors = [BadRequest, NotFound] as const;

const listObjectVersionsOp: Operation<
  typeof ListObjectVersionsInput,
  typeof VersionListResponse,
  typeof listObjectVersionsErrors
> = {
  id: "vault.listObjectVersions",
  method: "GET",
  retry: "transient",
  pathTemplate: "/vault/v1/kv/{id}/versions",
  pathParams: ["id"],
  queryParams: [],
  input: ListObjectVersionsInput,
  output: VersionListResponse,
  errors: listObjectVersionsErrors,
};

/** Retrieve all versions for a specific object. */
export const listObjectVersions = (
  input: ListObjectVersionsInput,
): Effect.Effect<
  VersionListResponse,
  WorkosError<typeof listObjectVersionsErrors>,
  WorkosClient
> => run(listObjectVersionsOp, input);

// ===========================================================================
// vault.listObjects — GET /vault/v1/kv (cursor paginated)
// ===========================================================================

export const ListObjectsInput = Schema.Struct({
  limit: Schema.optional(Schema.Number),
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  order: Schema.optional(Schema.Literals(["asc", "desc"])),
  search: Schema.optional(Schema.String),
  updatedAfter: Schema.optional(Schema.String),
});
export interface ListObjectsInput extends Schema.Schema.Type<
  typeof ListObjectsInput
> {}

const listObjectsErrors = [BadRequest] as const;

const listObjectsOp: Operation<
  typeof ListObjectsInput,
  typeof ObjectListResponse,
  typeof listObjectsErrors
> = {
  id: "vault.listObjects",
  method: "GET",
  retry: "transient",
  pathTemplate: "/vault/v1/kv",
  pathParams: [],
  queryParams: ["limit", "before", "after", "order", "search", "updatedAfter"],
  input: ListObjectsInput,
  output: ObjectListResponse,
  errors: listObjectsErrors,
};

/** List all encrypted objects with cursor-based pagination. */
export const listObjects = (
  input: ListObjectsInput = {},
): Effect.Effect<
  ObjectListResponse,
  WorkosError<typeof listObjectsErrors>,
  WorkosClient
> => run(listObjectsOp, input);

const listObjectsPagination: Pagination.CursorPagination<
  ListObjectsInput,
  ObjectListResponse,
  ObjectSummary
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of vault, following the `after` cursor. */
export const listObjectsPages = (
  input: ListObjectsInput = {},
): Stream.Stream<
  ObjectListResponse,
  WorkosError<typeof listObjectsErrors>,
  WorkosClient
> => Pagination.pages(listObjects, input, listObjectsPagination);

/** Stream every object summary across every page. */
export const listObjectsItems = (
  input: ListObjectsInput = {},
): Stream.Stream<
  ObjectSummary,
  WorkosError<typeof listObjectsErrors>,
  WorkosClient
> => Pagination.items(listObjects, input, listObjectsPagination);

// ===========================================================================
// vault.rekeyDataKey — POST /vault/v1/keys/rekey
// ===========================================================================

export const RekeyDataKeyInput = Schema.Struct({
  context: Schema.Record(Schema.String, Schema.String),
  encrypted_keys: Schema.String,
});
export interface RekeyDataKeyInput extends Schema.Schema.Type<
  typeof RekeyDataKeyInput
> {}

const rekeyDataKeyErrors = [BadRequest, UnprocessableEntity] as const;

const rekeyDataKeyOp: Operation<
  typeof RekeyDataKeyInput,
  typeof CreateDataKeyResponse,
  typeof rekeyDataKeyErrors
> = {
  id: "vault.rekeyDataKey",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/vault/v1/keys/rekey",
  pathParams: [],
  queryParams: [],
  input: RekeyDataKeyInput,
  output: CreateDataKeyResponse,
  errors: rekeyDataKeyErrors,
};

/** Decrypt an existing data key and re-encrypt it under a new key context. */
export const rekeyDataKey = (
  input: RekeyDataKeyInput,
): Effect.Effect<
  CreateDataKeyResponse,
  WorkosError<typeof rekeyDataKeyErrors>,
  WorkosClient
> => run(rekeyDataKeyOp, input);

// ===========================================================================
// vault.updateObject — PUT /vault/v1/kv/{id}
// ===========================================================================

export const UpdateObjectInput = Schema.Struct({
  id: Schema.String,
  value: Schema.String,
  version_check: Schema.optional(Schema.NullOr(Schema.String)),
});
export interface UpdateObjectInput extends Schema.Schema.Type<
  typeof UpdateObjectInput
> {}

const updateObjectErrors = [BadRequest, Conflict] as const;

const updateObjectOp: Operation<
  typeof UpdateObjectInput,
  typeof ObjectWithoutValue,
  typeof updateObjectErrors
> = {
  id: "vault.updateObject",
  method: "PUT",
  retry: "throttling",
  pathTemplate: "/vault/v1/kv/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: UpdateObjectInput,
  output: ObjectWithoutValue,
  errors: updateObjectErrors,
};

/** Update the value of an existing encrypted object. */
export const updateObject = (
  input: UpdateObjectInput,
): Effect.Effect<
  ObjectWithoutValue,
  WorkosError<typeof updateObjectErrors>,
  WorkosClient
> => run(updateObjectOp, input);
