/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry, pagination → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  Conflict,
  NotFound,
  type Operation,
  Pagination,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import type * as Stream from "effect/Stream";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import { InvalidRequestParameters, InvalidUrl } from "../errors.ts";
import { WebhookEndpointJson, WebhookEndpointList } from "../schemas.ts";

// ===========================================================================
// webhooks.create — POST /webhook_endpoints
// ===========================================================================

export const CreateWebhookEndpointInput = Schema.Struct({
  endpoint_url: Schema.String,
  events: Schema.Array(
    Schema.Literals([
      "agent.registration.created",
      "agent.registration.claim.attempt.created",
      "agent.registration.claim.completed",
      "agent.registration.credential.issued",
      "agent.registration.deleted",
      "agent.registration.expired",
      "agent.registration.organization.switched",
      "agent.registration.revoked",
      "authentication.email_verification_succeeded",
      "authentication.magic_auth_failed",
      "authentication.magic_auth_succeeded",
      "authentication.mfa_succeeded",
      "authentication.oauth_failed",
      "authentication.oauth_succeeded",
      "authentication.password_failed",
      "authentication.password_succeeded",
      "authentication.passkey_failed",
      "authentication.passkey_succeeded",
      "authentication.sso_failed",
      "authentication.sso_started",
      "authentication.sso_succeeded",
      "authentication.sso_timed_out",
      "radar.challenge_created",
      "authentication.radar_risk_detected",
      "authentication.reauthentication_succeeded",
      "api_key.created",
      "api_key.revoked",
      "api_key.updated",
      "connection.activated",
      "connection.deactivated",
      "connection.saml_certificate_renewal_required",
      "connection.saml_certificate_renewed",
      "connection.deleted",
      "dsync.activated",
      "dsync.deleted",
      "dsync.group.created",
      "dsync.group.deleted",
      "dsync.group.updated",
      "dsync.group.user_added",
      "dsync.group.user_removed",
      "dsync.user.created",
      "dsync.user.deleted",
      "dsync.user.updated",
      "email_verification.created",
      "group.created",
      "group.deleted",
      "group.member_added",
      "group.member_removed",
      "group.updated",
      "flag.created",
      "flag.deleted",
      "flag.updated",
      "flag.rule_updated",
      "invitation.accepted",
      "invitation.created",
      "invitation.resent",
      "invitation.revoked",
      "magic_auth.created",
      "organization.created",
      "organization.deleted",
      "organization.updated",
      "organization_domain.created",
      "organization_domain.deleted",
      "organization_domain.updated",
      "organization_domain.verified",
      "organization_domain.verification_failed",
      "password_reset.created",
      "password_reset.succeeded",
      "user.created",
      "user.updated",
      "user.deleted",
      "organization_membership.created",
      "organization_membership.deleted",
      "organization_membership.updated",
      "role.created",
      "role.deleted",
      "role.updated",
      "organization_role.created",
      "organization_role.deleted",
      "organization_role.updated",
      "permission.created",
      "permission.deleted",
      "permission.updated",
      "pipes.connected_account.connected",
      "pipes.connected_account.connection_failed",
      "pipes.connected_account.disconnected",
      "pipes.connected_account.reauthorization_needed",
      "session.created",
      "session.revoked",
      "waitlist_user.approved",
      "waitlist_user.created",
      "waitlist_user.denied",
    ]),
  ),
});
export interface CreateWebhookEndpointInput extends Schema.Schema.Type<
  typeof CreateWebhookEndpointInput
> {}

const createErrors = [Conflict, InvalidRequestParameters, InvalidUrl] as const;

const createOp: Operation<
  typeof CreateWebhookEndpointInput,
  typeof WebhookEndpointJson,
  typeof createErrors
> = {
  id: "webhooks.create",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/webhook_endpoints",
  pathParams: [],
  queryParams: [],
  input: CreateWebhookEndpointInput,
  output: WebhookEndpointJson,
  errors: createErrors,
};

/** Create a new webhook endpoint to receive event notifications. */
export const create = (
  input: CreateWebhookEndpointInput,
): Effect.Effect<
  WebhookEndpointJson,
  WorkosError<typeof createErrors>,
  WorkosClient
> => run(createOp, input);

// ===========================================================================
// webhooks.delete — DELETE /webhook_endpoints/{id}
// ===========================================================================

export const DeleteWebhookEndpointInput = Schema.Struct({
  id: Schema.String,
});
export interface DeleteWebhookEndpointInput extends Schema.Schema.Type<
  typeof DeleteWebhookEndpointInput
> {}

const deleteErrors = [NotFound] as const;

const deleteOp: Operation<
  typeof DeleteWebhookEndpointInput,
  typeof Schema.Void,
  typeof deleteErrors
> = {
  id: "webhooks.delete",
  method: "DELETE",
  retry: "throttling",
  pathTemplate: "/webhook_endpoints/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: DeleteWebhookEndpointInput,
  output: Schema.Void,
  errors: deleteErrors,
};

/** Delete an existing webhook endpoint. */
const deleteWebhookEndpoint = (
  input: DeleteWebhookEndpointInput,
): Effect.Effect<void, WorkosError<typeof deleteErrors>, WorkosClient> =>
  run(deleteOp, input);

// `delete` is a reserved word as a declaration name but a legal export name;
// the rename-export keeps the public surface on the API's own verb.
export { deleteWebhookEndpoint as delete };

// ===========================================================================
// webhooks.list — GET /webhook_endpoints (cursor paginated)
// ===========================================================================

export const ListWebhookEndpointsInput = Schema.Struct({
  before: Schema.optional(Schema.String),
  after: Schema.optional(Schema.String),
  limit: Schema.optional(Schema.Number),
  order: Schema.optional(Schema.Literals(["normal", "desc", "asc"])),
});
export interface ListWebhookEndpointsInput extends Schema.Schema.Type<
  typeof ListWebhookEndpointsInput
> {}

const listErrors = [] as const;

const listOp: Operation<
  typeof ListWebhookEndpointsInput,
  typeof WebhookEndpointList,
  typeof listErrors
> = {
  id: "webhooks.list",
  method: "GET",
  retry: "transient",
  pathTemplate: "/webhook_endpoints",
  pathParams: [],
  queryParams: ["before", "after", "limit", "order"],
  input: ListWebhookEndpointsInput,
  output: WebhookEndpointList,
  errors: listErrors,
};

/** Get a list of all of your existing webhook endpoints. */
export const list = (
  input: ListWebhookEndpointsInput = {},
): Effect.Effect<
  WebhookEndpointList,
  WorkosError<typeof listErrors>,
  WorkosClient
> => run(listOp, input);

const listPagination: Pagination.CursorPagination<
  ListWebhookEndpointsInput,
  WebhookEndpointList,
  WebhookEndpointJson
> = {
  cursorParam: "after",
  clear: ["before"],
  nextCursor: (page) => page.list_metadata.after,
  items: (page) => page.data,
};

/** Stream every page of webhooks, following the `after` cursor. */
export const listPages = (
  input: ListWebhookEndpointsInput = {},
): Stream.Stream<
  WebhookEndpointList,
  WorkosError<typeof listErrors>,
  WorkosClient
> => Pagination.pages(list, input, listPagination);

/** Stream every webhook endpoint json across every page. */
export const listItems = (
  input: ListWebhookEndpointsInput = {},
): Stream.Stream<
  WebhookEndpointJson,
  WorkosError<typeof listErrors>,
  WorkosClient
> => Pagination.items(list, input, listPagination);

// ===========================================================================
// webhooks.update — PATCH /webhook_endpoints/{id}
// ===========================================================================

export const UpdateWebhookEndpointInput = Schema.Struct({
  id: Schema.String,
  endpoint_url: Schema.optional(Schema.String),
  status: Schema.optional(Schema.Literals(["enabled", "disabled"])),
  events: Schema.optional(
    Schema.Array(
      Schema.Literals([
        "agent.registration.created",
        "agent.registration.claim.attempt.created",
        "agent.registration.claim.completed",
        "agent.registration.credential.issued",
        "agent.registration.deleted",
        "agent.registration.expired",
        "agent.registration.organization.switched",
        "agent.registration.revoked",
        "authentication.email_verification_succeeded",
        "authentication.magic_auth_failed",
        "authentication.magic_auth_succeeded",
        "authentication.mfa_succeeded",
        "authentication.oauth_failed",
        "authentication.oauth_succeeded",
        "authentication.password_failed",
        "authentication.password_succeeded",
        "authentication.passkey_failed",
        "authentication.passkey_succeeded",
        "authentication.sso_failed",
        "authentication.sso_started",
        "authentication.sso_succeeded",
        "authentication.sso_timed_out",
        "radar.challenge_created",
        "authentication.radar_risk_detected",
        "authentication.reauthentication_succeeded",
        "api_key.created",
        "api_key.revoked",
        "api_key.updated",
        "connection.activated",
        "connection.deactivated",
        "connection.saml_certificate_renewal_required",
        "connection.saml_certificate_renewed",
        "connection.deleted",
        "dsync.activated",
        "dsync.deleted",
        "dsync.group.created",
        "dsync.group.deleted",
        "dsync.group.updated",
        "dsync.group.user_added",
        "dsync.group.user_removed",
        "dsync.user.created",
        "dsync.user.deleted",
        "dsync.user.updated",
        "email_verification.created",
        "group.created",
        "group.deleted",
        "group.member_added",
        "group.member_removed",
        "group.updated",
        "flag.created",
        "flag.deleted",
        "flag.updated",
        "flag.rule_updated",
        "invitation.accepted",
        "invitation.created",
        "invitation.resent",
        "invitation.revoked",
        "magic_auth.created",
        "organization.created",
        "organization.deleted",
        "organization.updated",
        "organization_domain.created",
        "organization_domain.deleted",
        "organization_domain.updated",
        "organization_domain.verified",
        "organization_domain.verification_failed",
        "password_reset.created",
        "password_reset.succeeded",
        "user.created",
        "user.updated",
        "user.deleted",
        "organization_membership.created",
        "organization_membership.deleted",
        "organization_membership.updated",
        "role.created",
        "role.deleted",
        "role.updated",
        "organization_role.created",
        "organization_role.deleted",
        "organization_role.updated",
        "permission.created",
        "permission.deleted",
        "permission.updated",
        "pipes.connected_account.connected",
        "pipes.connected_account.connection_failed",
        "pipes.connected_account.disconnected",
        "pipes.connected_account.reauthorization_needed",
        "session.created",
        "session.revoked",
        "waitlist_user.approved",
        "waitlist_user.created",
        "waitlist_user.denied",
      ]),
    ),
  ),
});
export interface UpdateWebhookEndpointInput extends Schema.Schema.Type<
  typeof UpdateWebhookEndpointInput
> {}

const updateErrors = [
  Conflict,
  InvalidRequestParameters,
  InvalidUrl,
  NotFound,
] as const;

const updateOp: Operation<
  typeof UpdateWebhookEndpointInput,
  typeof WebhookEndpointJson,
  typeof updateErrors
> = {
  id: "webhooks.update",
  method: "PATCH",
  retry: "throttling",
  pathTemplate: "/webhook_endpoints/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: UpdateWebhookEndpointInput,
  output: WebhookEndpointJson,
  errors: updateErrors,
};

/** Update the properties of an existing webhook endpoint. */
export const update = (
  input: UpdateWebhookEndpointInput,
): Effect.Effect<
  WebhookEndpointJson,
  WorkosError<typeof updateErrors>,
  WorkosClient
> => run(updateOp, input);
