/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the WorkOS OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  BadRequest,
  NotFound,
  type Operation,
  UnprocessableEntity,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { run, type WorkosClient, type WorkosError } from "../client.ts";
import { WidgetSessionTokenResponse } from "../schemas.ts";

// ===========================================================================
// widgets.getToken — POST /widgets/token
// ===========================================================================

export const GetWidgetTokenInput = Schema.Struct({
  organization_id: Schema.optional(Schema.String),
  user_id: Schema.optional(Schema.String),
  scopes: Schema.optional(
    Schema.Array(
      Schema.Literals([
        "widgets:users-table:manage",
        "widgets:domain-verification:manage",
        "widgets:sso:manage",
        "widgets:api-keys:manage",
        "widgets:dsync:manage",
        "widgets:audit-log-streaming:manage",
        "widgets:pipes:manage",
      ]),
    ),
  ),
});
export interface GetWidgetTokenInput extends Schema.Schema.Type<
  typeof GetWidgetTokenInput
> {}

const getTokenErrors = [BadRequest, NotFound, UnprocessableEntity] as const;

const getTokenOp: Operation<
  typeof GetWidgetTokenInput,
  typeof WidgetSessionTokenResponse,
  typeof getTokenErrors
> = {
  id: "widgets.getToken",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/widgets/token",
  pathParams: [],
  queryParams: [],
  input: GetWidgetTokenInput,
  output: WidgetSessionTokenResponse,
  errors: getTokenErrors,
};

/** Generate a widget token for a user, optionally scoped to an organization. When an organization is specified, org-scoped widgets are enabled; omitting it issues a user-only token for widgets like `UserProfile` and `UserSecurity`. */
export const getToken = (
  input: GetWidgetTokenInput = {},
): Effect.Effect<
  WidgetSessionTokenResponse,
  WorkosError<typeof getTokenErrors>,
  WorkosClient
> => run(getTokenOp, input);
