/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the Mosaic OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  NotFound,
  type Operation,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { type MosaicClient, type MosaicError, run } from "../client.ts";
import { Account } from "../schemas.ts";

// ===========================================================================
// accounts.create — POST /accounts
// ===========================================================================

export const CreateAccountInput = Schema.Struct({ name: Schema.String });
export interface CreateAccountInput extends Schema.Schema.Type<
  typeof CreateAccountInput
> {}

const createErrors = [NotFound] as const;

const createOp: Operation<
  typeof CreateAccountInput,
  typeof Account,
  typeof createErrors
> = {
  id: "accounts.create",
  method: "POST",
  retry: "throttling",
  pathTemplate: "/accounts",
  pathParams: [],
  queryParams: [],
  input: CreateAccountInput,
  output: Account,
  errors: createErrors,
};

/** Create an account. */
export const create = (
  input: CreateAccountInput,
): Effect.Effect<Account, MosaicError<typeof createErrors>, MosaicClient> =>
  run(createOp, input);

// ===========================================================================
// accounts.get — GET /accounts/{id}
// ===========================================================================

export const GetAccountInput = Schema.Struct({ id: Schema.String });
export interface GetAccountInput extends Schema.Schema.Type<
  typeof GetAccountInput
> {}

const getErrors = [NotFound] as const;

const getOp: Operation<
  typeof GetAccountInput,
  typeof Account,
  typeof getErrors
> = {
  id: "accounts.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/accounts/{id}",
  pathParams: ["id"],
  queryParams: [],
  input: GetAccountInput,
  output: Account,
  errors: getErrors,
};

/** Fetch an account. */
export const get = (
  input: GetAccountInput,
): Effect.Effect<Account, MosaicError<typeof getErrors>, MosaicClient> =>
  run(getOp, input);
