/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the Mosaic OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  NotFound,
  type Operation,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { type MosaicClient, type MosaicError, run } from "../client.ts";
import { ZoneList } from "../schemas.ts";

// ===========================================================================
// zones.list — GET /zones
// ===========================================================================

export const ListZonesInput = Schema.Struct({});
export interface ListZonesInput extends Schema.Schema.Type<
  typeof ListZonesInput
> {}

const listErrors = [NotFound] as const;

const listOp: Operation<
  typeof ListZonesInput,
  typeof ZoneList,
  typeof listErrors
> = {
  id: "zones.list",
  method: "GET",
  retry: "transient",
  pathTemplate: "/zones",
  pathParams: [],
  queryParams: [],
  input: ListZonesInput,
  output: ZoneList,
  errors: listErrors,
};

/** List zones. */
export const list = (
  input: ListZonesInput = {},
): Effect.Effect<ZoneList, MosaicError<typeof listErrors>, MosaicClient> =>
  run(listOp, input);
