/**
 * @generated by @hourglass-financial/api-factory — DO NOT EDIT.
 *
 * This file is machine-owned; hand edits are overwritten on regeneration.
 * Change the source of truth instead:
 *   - operation surface / wire shapes / errors → the Union Success OpenAPI spec
 *   - request execution, retry → @hourglass-financial/api-factory-core
 *
 * Uniform per-operation blocks: input schema + type, a declarative descriptor,
 * and a thin exported function that dispatches through `run`.
 */
import {
  NotFound,
  type Operation,
} from "@hourglass-financial/api-factory-core";
import type * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import {
  run,
  type UnionSuccessClient,
  type UnionSuccessError,
} from "../client.ts";
import { CompletedJob, PendingJob } from "../schemas.ts";

// ===========================================================================
// jobs.get — GET /jobs
// ===========================================================================

export const GetJobInput = Schema.Struct({});
export interface GetJobInput extends Schema.Schema.Type<typeof GetJobInput> {}

const getErrors = [NotFound] as const;

const getOp: Operation<
  typeof GetJobInput,
  Schema.Union<readonly [typeof PendingJob, typeof CompletedJob]>,
  typeof getErrors
> = {
  id: "jobs.get",
  method: "GET",
  retry: "transient",
  pathTemplate: "/jobs",
  pathParams: [],
  queryParams: [],
  input: GetJobInput,
  output: Schema.Union([PendingJob, CompletedJob]),
  errors: getErrors,
};

/** Get a job in either success state. */
export const get = (
  input: GetJobInput = {},
): Effect.Effect<
  PendingJob | CompletedJob,
  UnionSuccessError<typeof getErrors>,
  UnionSuccessClient
> => run(getOp, input);
